/*-----------------EXCEPTION FILES----------------------

	1)	BANKRUPTCY FILE
	2)	DECEASED EXCEPTION FILE
	3)	LITIGIOUS EXCEPTION FILE
	4)	MILITARY EXCEPTION FILE


-------------------------------------------------------*/


		/*BANKRUPTCY EXCEPTION FILE*/

/*PULL IN LN_WATERFALL*/
DATA BANKRUPTCY_EXCEPTION_LN_PRE (KEEP= ACCOUNT_NUMBER UNIQUE_NUMBER CLIENT_CODE CLIENT_INPUT_SSN CLIENT_FIRST_NAME CLIENT_LAST_NAME BKR_FLAG
									    CASE_NUMBER CHAPTER FILE_DATE STATUS_DATE DISPOSITION_CODE SUFFIX ADDRESS ZIP_CODE SOCIAL_SECURITY_NUMBER 
   										CITY_FILED STATE_FILED COUNTY FIRST_NAME MIDDLE_NAME LAST_NAME BUSINESS BUSINESS_1 BUSINESS_2 
   										BUSINESS_3 DEBTOR_S_CITY DEBTOR_S_STATE ECOA LAW_FIRM ATTORNEY_NAME ATTORNEY_ADDRESS 
 										ATTORNEY_CITY ATTORNEY_STATE ATTORNEY_ZIP ATTORNEY_PHONE ATTORNEY_EMAIL ATTORNEY_FAX 
          							    _341_DATE _341_TIME _341_LOCATION TRUSTEE TRUSTEE_ADDRESS TRUSTEE_CITY 
          								TRUSTEE_STATE TRUSTEE_ZIP TRUSTEE_PHONE JUDGE_S_INITIALS FUNDS DISCHARGE_COMPLAINT_BAR_DATE MATCH_CODE COURT_DISTRICT 
          								COURT_ADDRESS_1 COURT_ADDRESS_2 COURT_MAILING_CITY COURT_ZIP COURT_PHONE 
          								DEBTOR_PHONE VOLUNTARY_INVOLUNTARY_DISMISSAL PROOF_OF_CLAIM_DATE MULTIPLE_DEBTOR 
          								COURT_ID TRUSTEE_ID REINSTATED_CASE_DATE CLOSED_DATE CLIENT_UPDATE_FLAG FILING_STATUS);
	SET	LN_OUTPUT_LNWATERFALL_INPUT_EBG;
	WHERE BKR_FLAG = 'Y';
RUN;

DATA BANKRUPTCY_EXCEPTION_LN_PRE2 (KEEP=ACCOUNT_ID CLIENT_ACCOUNT_ID ISSUER_ACCOUNT_NUMBER
										EXCEPTION_SUB_TYPE DEBTOR_SSN DATE_FILE CASE_NUMBER
									    CHAPTER CASE_CONVERTED ORIGINAL_CHAPTER _341_MEETING_DATE
										_341_MEETING_TIME _341_LOCATION BAR_DATE FILE_VOLUNTARILY
										HAS_ASSETS FILE_PROSE DISPOSITION DATE_DISMISSED DATE_DISCHARGED
										DATE_CLOSED STATUS_LAST_CHANGED PLAN_CONFIRMATION_DATE POC_FILED_DATE
										POC_CLAIM_NUMBER POC_DUE_DATE COURT_NAME COURT_DISTRICT COURT_DIVISION
										COURT_ADDRESS COURT_CITY COURT_STATE COURT_ZIPCODE COURT_PHONE LAW_FIRM_NAME
										ATTORNEY_NAME ATTORNEY_ADDRESS ATTORNEY_CITY ATTORNEY_STATE ATTORNEY_ZIP
										ATTORNEY_PHONE TRUSTEE_NAME TRUSTEE_ADDRESS TRUSTEE_CITY TRUSTEE_STATE
										TRUSTEE_ZIP TRUSTEE_PHONE COMMENTS TYPE);
	SET BANKRUPTCY_EXCEPTION_LN_PRE;
/*	ACCOUNT_ID = '';*/
	CLIENT_ACCOUNT_ID = '';
	ISSUER_ACCOUNT_NUMBER = ACCOUNT_NUMBER;
	EXCEPTION_SUB_TYPE = '';
	DEBTOR_SSN = CLIENT_INPUT_SSN;
	DATE_FILE = PUT(INPUT(FILE_DATE,YYMMDD8.),MMDDYY10.);
	CASE_NUMBER = CASE_NUMBER;
	CHAPTER 	= CHAPTER;
	CASE_CONVERTED = '';
	ORIGINAL_CHAPTER = '';
	_341_MEETING_DATE = PUT(INPUT(_341_DATE,YYMMDD8.),MMDDYY10.);
	_341_MEETING_TIME = _341_TIME;
	_341_LOCATION = _341_LOCATION;
	BAR_DATE = PUT(INPUT(DISCHARGE_COMPLAINT_BAR_DATE,YYMMDD8.),MMDDYY10.);;
	FILE_VOLUNTARILY = '';
	HAS_ASSETS = FUNDS;
	FILE_PROSE = '';
	DISPOSITION = DISPOSITION_CODE;
	DATE_DISMISSED = '';
	DATE_DISCHARGED = PUT(INPUT(DISCHARGE_COMPLAINT_BAR_DATE,YYMMDD8.),MMDDYY10.);
	DATE_CLOSED = PUT(INPUT(CLOSED_DATE,YYMMDD8.),MMDDYY10.);
	STATUS_LAST_CHANGED = '';
	PLAN_CONFIRMATION_DATE = '';
	POC_FILED_DATE = PUT(INPUT(PROOF_OF_CLAIM_DATE,YYMMDD8.),MMDDYY10.);
	POC_CLAIM_NUMBER = '';
	POC_DUE_DATE = '';
	COURT_NAME = '';
	COURT_DISTRICT = COURT_DISTRICT;
	COURT_DIVISION = '';
	COURT_ADDRESS = CATX(' ',COURT_ADDRESS_1,COURT_ADDRESS_2);
	COURT_CITY = COURT_MAILING_CITY;
	COURT_STATE = '';
	COURT_ZIPCODE = COURT_ZIP;
	COURT_PHONE = COURT_PHONE;
	LAW_FIRM_NAME = LAW_FIRM;
	ATTORNEY_NAME = ATTORNEY_NAME;
	ATTORNEY_ADDRESS = ATTORNEY_ADDRESS;
	ATTORNEY_CITY = ATTORNEY_CITY;
	ATTORNEY_STATE = ATTORNEY_STATE;
	ATTORNEY_ZIP = ATTORNEY_ZIP;
	ATTORNEY_PHONE = ATTORNEY_PHONE;
	TRUSTEE_NAME = TRUSTEE;
	TRUSTEE_ADDRESS = TRUSTEE_ADDRESS;
	TRUSTEE_CITY = TRUSTEE_CITY;
	TRUSTEE_STATE = TRUSTEE_STATE;
	TRUSTEE_ZIP = TRUSTEE_ZIP;
	TRUSTEE_PHONE = TRUSTEE_PHONE;
	COMMENTS = '';
	TYPE = 'LN WATERFALL BANKRUPTCY';
RUN;

/*PULL IN TLO_WATERFALL*/

DATA BANKRUPTCY_EXCEPTION_TLO_PRE;
	SET TLO_WATERFALL_INPUT_EBG;
	WHERE TLOBANKRUPTCYFLAG = 'Y';
RUN;

DATA BANKRUPTCY_EXCEPTION_TLO_PRE2 (KEEP=ACCOUNT_ID CLIENT_ACCOUNT_ID ISSUER_ACCOUNT_NUMBER
										EXCEPTION_SUB_TYPE DEBTOR_SSN DATE_FILE CASE_NUMBER
									    CHAPTER CASE_CONVERTED ORIGINAL_CHAPTER _341_MEETING_DATE
										_341_MEETING_TIME _341_LOCATION BAR_DATE FILE_VOLUNTARILY
										HAS_ASSETS FILE_PROSE DISPOSITION DATE_DISMISSED DATE_DISCHARGED
										DATE_CLOSED STATUS_LAST_CHANGED PLAN_CONFIRMATION_DATE POC_FILED_DATE
										POC_CLAIM_NUMBER POC_DUE_DATE COURT_NAME COURT_DISTRICT COURT_DIVISION
										COURT_ADDRESS COURT_CITY COURT_STATE COURT_ZIPCODE COURT_PHONE LAW_FIRM_NAME
										ATTORNEY_NAME ATTORNEY_ADDRESS ATTORNEY_CITY ATTORNEY_STATE ATTORNEY_ZIP
										ATTORNEY_PHONE TRUSTEE_NAME TRUSTEE_ADDRESS TRUSTEE_CITY TRUSTEE_STATE
										TRUSTEE_ZIP TRUSTEE_PHONE COMMENTS TYPE);
	SET BANKRUPTCY_EXCEPTION_TLO_PRE;
/*	ACCOUNT_ID = '';*/
	CLIENT_ACCOUNT_ID = '';
	ISSUER_ACCOUNT_NUMBER = CUSTOMER_ACCOUNT;
	EXCEPTION_SUB_TYPE = '';
	DEBTOR_SSN = SSN;
	DATE_FILE = TLOBANKRUPTCYFILEDATE;
	CASE_NUMBER = TLOBANKRUPTCYCASENUMBER;
	CHAPTER 	= TLOBANKRUPTCYCHAPTER;
	CASE_CONVERTED = TLOBANKRUPTCYCONVERTEDCHAPTER;
	ORIGINAL_CHAPTER = TLOBANKRUPTCYORIGINALCHAPTER;
	_341_MEETING_DATE = TLOBANKRUPTCY341DATE;
	_341_MEETING_TIME = TLOBANKRUPTCY341TIME;
	_341_LOCATION = TLOBANKRUPTCY341ADDRESSLINE1;
	BAR_DATE = TLOBANKRUPTCYBARDATE;
	FILE_VOLUNTARILY = TLOBANKRUPTCYVOLUNTARYFLAG;
	HAS_ASSETS = TLOBANKRUPTCYASSETSINDICATOR;
	FILE_PROSE = TLOBANKRUPTCYPROSEINDICATOR;
	DISPOSITION = '';
	DATE_DISMISSED = TLOBANKRUPTCYDISMISSEDDATE;
	DATE_DISCHARGED = TLOBANKRUPTCYDISCHARGEDATE;
	DATE_CLOSED = TLOBANKRUPTCYUPDATEDDATE;
	STATUS_LAST_CHANGED = '';
	PLAN_CONFIRMATION_DATE = '';
	POC_FILED_DATE = '';
	POC_CLAIM_NUMBER = '';
	POC_DUE_DATE = '';
	COURT_NAME = TLOBANKRUPTCYCOURTNAME;
	COURT_DISTRICT = TLOBANKRUPTCYCOURTDISTRICT;
	COURT_DIVISION = TLOBANKRUPTCYCOURTDIVISION;
	COURT_ADDRESS = TLOBANKRUPTCYCOURTADDRESS;
	COURT_CITY = TLOBANKRUPTCYCOURTADDRESSCITY;
	COURT_STATE = TLOBANKRUPTCYCOURTADDRESSSTATE;
	COURT_ZIPCODE = TLOBANKRUPTCYCOURTADDRESSZIP;
	COURT_PHONE = TLOBANKRUPTCYCOURTPHONE;
	LAW_FIRM_NAME = TLOBANKRUPTCYLAWFIRM;
	ATTORNEY_NAME = TLOBANKRUPTCYATTORNEYNAME;
	ATTORNEY_ADDRESS = TLOBANKRUPTCYATTORNEYADDRESS;
	ATTORNEY_CITY = TLOBANKRUPTCYATTORNEYADDRESSCITY;
	ATTORNEY_STATE = TLOBANKRUPTCYATTORNEYADDRESSSTAT;
	ATTORNEY_ZIP = TLOBANKRUPTCYATTORNEYADDRESSZIP;
	ATTORNEY_PHONE = TLOBANKRUPTCYATTORNEYPHONE;
	TRUSTEE_NAME = TLOBANKRUPTCYTRUSTEENAME;
	TRUSTEE_ADDRESS = TLOBANKRUPTCYTRUSTEEADDRESS;
	TRUSTEE_CITY = TLOBANKRUPTCYTRUSTEEADDRESSCITY;
	TRUSTEE_STATE = TLOBANKRUPTCYTRUSTEEADDRESSSTATE;
	TRUSTEE_ZIP = TLOBANKRUPTCYTRUSTEEADDRESSZIP;
	TRUSTEE_PHONE = '';
	COMMENTS = TLOBANKRUPTCYTRUSTEEPHONE;
	TYPE = 'TLO WATERFALL BANKRUPTCY';
RUN;

DATA BANKRUPTCY_TEMPLATE;
    LENGTH
/*        ACCOUNT_ID       $ 50*/
        CLIENT_ACCOUNT_ID $ 50
        ISSUER_ACCOUNT_NUMBER $ 50
        EXCEPTION_SUB_TYPE $ 50
        DEBTOR_SSN       $ 50
        DATE_FILE      $ 50
        CASE_NUMBER      $ 50
        CHAPTER          $ 50
        CASE_CONVERTED   $ 50
        ORIGINAL_CHAPTER $ 50
        _341_MEETING_DATE $ 50
        _341_MEETING_TIME $ 50
        _341_LOCATION $ 50
        BAR_DATE         $ 50
        FILE_VOLUNTARILY $ 50
        HAS_ASSETS       $ 50
        FILE_PROSE      $ 50
        DISPOSITION      $ 50
        DATE_DISMISSED   $ 50
        DATE_DISCHARGED  $ 50
        DATE_CLOSED      $ 50
        STATUS_LAST_CHANGED $ 50
        PLAN_CONFIRMATION_DATE $ 50
        POC_FILED_DATE  $ 50
        POC_CLAIM_NUMBER $ 50
        POC_DUE_DATE     $ 50
        COURT_NAME       $ 50
        COURT_DISTRICT   $ 50
        COURT_DIVISION   $ 50
        COURT_ADDRESS    $ 50
        COURT_CITY       $ 50
        COURT_STATE      $ 50
        COURT_ZIPCODE    $ 50
        COURT_PHONE      $ 50
        LAW_FIRM_NAME    $ 50
        ATTORNEY_NAME    $ 50
        ATTORNEY_ADDRESS $ 50
        ATTORNEY_CITY    $ 50
        ATTORNEY_STATE   $ 50
        ATTORNEY_ZIP $ 50
        ATTORNEY_PHONE   $ 50
        TRUSTEE_NAME     $ 50
        TRUSTEE_ADDRESS  $ 50
        TRUSTEE_CITY     $ 50
        TRUSTEE_STATE    $ 50
        TRUSTEE_ZIP  $ 50
        TRUSTEE_PHONE    $ 50
        COMMENTS         $ 50 
		TYPE 			 $ 50;
    FORMAT
/*        ACCOUNT_ID       $CHAR50.*/
        CLIENT_ACCOUNT_ID $CHAR50.
        ISSUER_ACCOUNT_NUMBER $CHAR50.
        EXCEPTION_SUB_TYPE $CHAR50.
        DEBTOR_SSN       $CHAR50.
        DATE_FILE       $CHAR50.
        CASE_NUMBER      $CHAR50.
        CHAPTER          $CHAR50.
        CASE_CONVERTED   $CHAR50.
        ORIGINAL_CHAPTER $CHAR50.
        _341_MEETING_DATE $CHAR50.
        _341_MEETING_TIME $CHAR50.
        _341_LOCATION $CHAR50.
        BAR_DATE         $CHAR50.
        FILE_VOLUNTARILY $CHAR50.
        HAS_ASSETS       $CHAR50.
        FILE_PROSE      $CHAR50.
        DISPOSITION      $CHAR50.
        DATE_DISMISSED   $CHAR50.
        DATE_DISCHARGED  $CHAR50.
        DATE_CLOSED      $CHAR50.
        STATUS_LAST_CHANGED $CHAR50.
        PLAN_CONFIRMATION_DATE $CHAR50.
        POC_FILED_DATE   $CHAR50.
        POC_CLAIM_NUMBER $CHAR50.
        POC_DUE_DATE     $CHAR50.
        COURT_NAME       $CHAR50.
        COURT_DISTRICT   $CHAR50.
        COURT_DIVISION   $CHAR50.
        COURT_ADDRESS    $CHAR50.
        COURT_CITY       $CHAR50.
        COURT_STATE      $CHAR50.
        COURT_ZIPCODE    $CHAR50.
        COURT_PHONE      $CHAR50.
        LAW_FIRM_NAME    $CHAR50.
        ATTORNEY_NAME    $CHAR50.
        ATTORNEY_ADDRESS $CHAR50.
        ATTORNEY_CITY    $CHAR50.
        ATTORNEY_STATE   $CHAR50.
        ATTORNEY_ZIP $CHAR50.
        ATTORNEY_PHONE   $CHAR50.
        TRUSTEE_NAME     $CHAR50.
        TRUSTEE_ADDRESS  $CHAR50.
        TRUSTEE_CITY     $CHAR50.
        TRUSTEE_STATE    $CHAR50.
        TRUSTEE_ZIP  $CHAR50.
        TRUSTEE_PHONE    $CHAR50.
        COMMENTS         $CHAR50. 
		TYPE 			 $CHAR50.;
RUN;


/*APPEND TLO/LN INTO BANKRUPTCY TEMPLATE*/

PROC APPEND BASE=BANKRUPTCY_TEMPLATE DATA=BANKRUPTCY_EXCEPTION_TLO_PRE2 FORCE;
RUN;

PROC APPEND BASE=BANKRUPTCY_TEMPLATE DATA=BANKRUPTCY_EXCEPTION_LN_PRE2 FORCE;
RUN;

DATA BANKRUPTCY_FINAL;
	SET BANKRUPTCY_TEMPLATE;
	WHERE TYPE^= '';
RUN;


/*NOW DECEASED EXCEPTION FILE*/

/*LNWATERFALL*/

DATA DECEASED_EXCEPTION_LN_PRE;
	SET	LN_OUTPUT_LNWATERFALL_INPUT_EBG;
	WHERE DEC_SSN ^= '' OR DEC_FNAME ^= '';
RUN;

DATA DECEASED_EXCEPTION_LN_PRE_2(KEEP=ACCOUNT_ID CLIENT_ACCOUNT_ID ISSUER_ACCOUNT_NUMBER EXCEPTION_SUB_TYPE DEBTOR_SSN DATE_OF_DEATH DATE_OF_BIRTH
									  LAST_RESIDENCE_ADDRESS LAST_RESIDENCE_STATE LAST_RESIDENCE_CITY LAST_RESIDENCE_ZIPCODE PROBATE_ATTORNEY_COMPANY
									  PROBATE_ATTORNEY_NAME PROBATE_ATTORNEY_ADDRESS PROBATE_ATTORNEY_STATE PROBATE_ATTORNEY_CITY PROBATE_ATTORNEY_ZIPCODE
									  PROBATE_ATTORNEY_PHONE COMMENTS TYPE);
	SET DECEASED_EXCEPTION_LN_PRE;
/*	ACCOUNT_ID = '';*/
	CLIENT_ACCOUNT_ID = '';
	ISSUER_ACCOUNT_NUMBER = ACCOUNT_NUMBER;
	EXCEPTION_SUB_TYPE = '';
	DEBTOR_SSN = CLIENT_INPUT_SSN;
	DATE_OF_DEATH = PUT(INPUT(DEC_DDATE,MMDDYY8.),MMDDYY10.);
	DATE_OF_BIRTH = PUT(INPUT(DEC_BDATE,MMDDYY8.),MMDDYY10.);
	LAST_RESIDENCE_ADDRESS = DEC_ADDRESS;
	LAST_RESIDENCE_CITY = DEC_CITY ;
	LAST_RESIDENCE_STATE = DEC_STATE;
	LAST_RESIDENCE_ZIPCODE = DEC_ZIP;
	PROBATE_ATTORNEY_COMPANY = LAW_FIRM;
	PROBATE_ATTORNEY_NAME = ATTORNEY_NAME;
	PROBATE_ATTORNEY_ADDRESS = ATTORNEY_ADDRESS;
	PROBATE_ATTORNEY_CITY = ATTORNEY_CITY;
	PROBATE_ATTORNEY_STATE = ATTORNEY_STATE;
	PROBATE_ATTORNEY_ZIPCODE = ATTORNEY_ZIP;
	PROBATE_ATTORNEY_PHONE = ATTORNEY_PHONE;
	COMMENTS = '';
	TYPE = 'LN WATERFALL DECEASED';
RUN;

	



/*GET TLO NOW*/
DATA DECEASED_EXCEPTION_TLO_PRE;
	SET	TLO_WATERFALL_INPUT_EBG;
	WHERE TLODATEOFDEATH ^= '';
RUN;

DATA DECEASED_EXCEPTION_TLO_PRE_2(KEEP=ACCOUNT_ID CLIENT_ACCOUNT_ID ISSUER_ACCOUNT_NUMBER EXCEPTION_SUB_TYPE DEBTOR_SSN DATE_OF_DEATH DATE_OF_BIRTH
									  LAST_RESIDENCE_ADDRESS LAST_RESIDENCE_STATE LAST_RESIDENCE_CITY LAST_RESIDENCE_ZIPCODE PROBATE_ATTORNEY_COMPANY
									  PROBATE_ATTORNEY_NAME PROBATE_ATTORNEY_ADDRESS PROBATE_ATTORNEY_STATE PROBATE_ATTORNEY_CITY PROBATE_ATTORNEY_ZIPCODE
									  PROBATE_ATTORNEY_PHONE COMMENTS TYPE);
	SET DECEASED_EXCEPTION_TLO_PRE;
/*	ACCOUNT_ID = '';*/
	CLIENT_ACCOUNT_ID = '';
	ISSUER_ACCOUNT_NUMBER = CUSTOMER_ACCOUNT;
	EXCEPTION_SUB_TYPE = '';
	DEBTOR_SSN = SSN;
	DATE_OF_DEATH = TLODATEOFDEATH;
	DATE_OF_BIRTH = '';
	LAST_RESIDENCE_ADDRESS = TLOADDRESS1LINE1;
	LAST_RESIDENCE_CITY = TLOADDRESS1CITY ;
	LAST_RESIDENCE_STATE = TLOADDRESS1STATE;
	LAST_RESIDENCE_ZIPCODE = TLOADDRESS1ZIP;
	PROBATE_ATTORNEY_COMPANY = TLOBANKRUPTCYLAWFIRM;
	PROBATE_ATTORNEY_NAME = TLOBANKRUPTCYATTORNEYNAME;
	PROBATE_ATTORNEY_ADDRESS = TLOBANKRUPTCYATTORNEYADDRESS;
	PROBATE_ATTORNEY_CITY = TLOBANKRUPTCYATTORNEYADDRESSCITY;
	PROBATE_ATTORNEY_STATE = TLOBANKRUPTCYTRUSTEEADDRESSSTATE;
	PROBATE_ATTORNEY_ZIPCODE = TLOBANKRUPTCYTRUSTEEADDRESSZIP;
	PROBATE_ATTORNEY_PHONE = TLOBANKRUPTCYATTORNEYPHONE;
	COMMENTS = '';
	TYPE = 'TLO WATERFALL DECEASED';
RUN;

DATA DECEASEDTEMPLATE;
    LENGTH
/*        ACCOUNT_ID       $ 50*/
        CLIENT_ACCOUNT_ID $ 50
        ISSUER_ACCOUNT_NUMBER $ 50
        EXCEPTION_SUB_TYPE $ 50
        DEBTOR_SSN       $ 50
        DATE_OF_DEATH    $ 50
        DATE_OF_BIRTH    $ 50
        LAST_RESIDENCE_ADDRESS $ 50
        LAST_RESIDENCE_CITY $ 50
        LAST_RESIDENCE_STATE $ 50
        LAST_RESIDENCE_ZIPCODE $ 50
        PROBATE_ATTORNEY_COMPANY $ 50
        PROBATE_ATTORNEY_NAME $ 50
        PROBATE_ATTORNEY_ADDRESS $ 50
        PROBATE_ATTORNEY_CITY $ 50
        PROBATE_ATTORNEY_STATE $ 50
        PROBATE_ATTORNEY_ZIPCODE $ 50
        PROBATE_ATTORNEY_PHONE $ 50
        COMMENTS         $ 50 
		TYPE			 $ 50;
    FORMAT
/*        ACCOUNT_ID       $CHAR50.*/
        CLIENT_ACCOUNT_ID $CHAR50.
        ISSUER_ACCOUNT_NUMBER $CHAR50.
        EXCEPTION_SUB_TYPE $CHAR50.
        DEBTOR_SSN       $CHAR50.
        DATE_OF_DEATH    $CHAR50.
        DATE_OF_BIRTH    $CHAR50.
        LAST_RESIDENCE_ADDRESS $CHAR50.
        LAST_RESIDENCE_CITY $CHAR50.
        LAST_RESIDENCE_STATE $CHAR50.
        LAST_RESIDENCE_ZIPCODE $CHAR50.
        PROBATE_ATTORNEY_COMPANY $CHAR50.
        PROBATE_ATTORNEY_NAME $CHAR50.
        PROBATE_ATTORNEY_ADDRESS $CHAR50.
        PROBATE_ATTORNEY_CITY $CHAR50.
        PROBATE_ATTORNEY_STATE $CHAR50.
        PROBATE_ATTORNEY_ZIPCODE $CHAR50.
        PROBATE_ATTORNEY_PHONE $CHAR50.
        COMMENTS         $CHAR50. 
		TYPE			 $CHAR50.;
RUN;

PROC APPEND BASE=DECEASEDTEMPLATE DATA=DECEASED_EXCEPTION_TLO_PRE_2 FORCE;
RUN;

PROC APPEND BASE=DECEASEDTEMPLATE DATA=DECEASED_EXCEPTION_LN_PRE_2 FORCE;
RUN;

DATA DECEASED_FINAL;
	SET DECEASEDTEMPLATE;
	WHERE ISSUER_ACCOUNT_NUMBER ^= '';
RUN;


/*CREATE LITIGIOUS FILES*/


/*PULL IN LN_WATERFALL*/
DATA LITIGIOUS_EXCEPTION_LN_PRE;
	SET	LN_OUTPUT_LNWATERFALL_INPUT_EBG;
	WHERE LITIGIOUSDEBTOR_FLAG ^= '';
RUN;

DATA LITIGIOUS_EXCEPTION_LN_PRE2 (KEEP=ACCOUNT_ID CLIENT_ACCOUNT_ID ISSUER_ACCOUNT_NUMBER EXCEPTION_SUB_TYPE DEBTOR_SSN NUMBER_OF_FILINGS SCORE COMMENTS TYPE);
	SET LITIGIOUS_EXCEPTION_LN_PRE;
/*	ACCOUNT_ID = '';*/
	CLIENT_ACCOUNT_ID = '';
	ISSUER_ACCOUNT_NUMBER = ACCOUNT_NUMBER;
	EXCEPTION_SUB_TYPE = '';
	DEBTOR_SSN = CLIENT_INPUT_SSN;
	NUMBER_OF_FILINGS = '';
	SCORE = '';
	COMMENTS = '';
	TYPE = 'LEXISNEXIS LITIGIOUS DEBTOR';
RUN;

DATA LITIGIOUSTEMPLATE;
    LENGTH
/*        ACCOUNT_ID        $ 50*/
        CLIENT_ACCOUNT_ID $ 50
        ISSUER_ACCOUNT_NUMBER $ 50
        EXCEPTION_SUB_TYPE $ 50
        DEBTOR_SSN       $ 50
        NUMBER_OF_FILINGS $ 50
        SCORE            $ 50
        COMMENTS         $ 50
		TYPE			 $ 50;
    FORMAT
/*        ACCOUNT_ID       $CHAR50.*/
        CLIENT_ACCOUNT_ID $CHAR50.
        ISSUER_ACCOUNT_NUMBER $CHAR50.
        EXCEPTION_SUB_TYPE $CHAR50.
        DEBTOR_SSN       $CHAR50.
        NUMBER_OF_FILINGS $CHAR50.
        SCORE            $CHAR50.
        COMMENTS         $CHAR50.
		TYPE			 $CHAR50.;
RUN;

PROC APPEND BASE=LITIGIOUSTEMPLATE DATA=LITIGIOUS_EXCEPTION_LN_PRE2 FORCE;
RUN;

DATA LITIGIOUS_FINAL;
	SET LITIGIOUSTEMPLATE;
	WHERE ISSUER_ACCOUNT_NUMBER ^= '';
RUN;



/*CREATE MILITARY EXCEPTION*/










/*---------------------------*/




/*ADD ACCOUNTID TO THESE EXCEPTION FILES FROM THE BEAM EXTRACT*/


PROC SQL;
	CREATE TABLE LITIGIOUS_FINAL_EXCEPTIONS AS
	SELECT  B.ACCOUNTID			AS ACCOUNT_ID
		   ,A.*
	FROM LITIGIOUS_FINAL A
	LEFT JOIN BEAM_ACCT_EXTRACT B
		ON (COMPRESS(A.ISSUER_ACCOUNT_NUMBER) = COMPRESS(B.ISSUERACCOUNTNUMBER))
;
PROC SQL;
	CREATE TABLE DECEASED_FINAL_EXCEPTIONS AS
	SELECT B.ACCOUNTID			AS ACCOUNT_ID
		  ,A.*
	FROM DECEASED_FINAL A
	LEFT JOIN BEAM_ACCT_EXTRACT B
		ON (COMPRESS(A.ISSUER_ACCOUNT_NUMBER) = COMPRESS(B.ISSUERACCOUNTNUMBER))
;
PROC SQL;
	CREATE TABLE BANKRUPTCY_FINAL_EXCEPTIONS AS
	SELECT B.ACCOUNTID			AS ACCOUNT_ID
		  ,A.*
	FROM BANKRUPTCY_FINAL A
	LEFT JOIN BEAM_ACCT_EXTRACT B
		ON (COMPRESS(A.ISSUER_ACCOUNT_NUMBER) = COMPRESS(B.ISSUERACCOUNTNUMBER))
;
/*ADD MILITARY TO THIS*/
QUIT;


