/*-----------------------------------------------------------

	DATA SERVICES INPUT TREE

	AUTHOR: JUSTIN HUBBARD

	GOAL: SPLIT UP IMPORTED CLIENT DATA INTO ACCEPTABLE FORMATED DATASETS TO THEN SEND OUT TO DATA SERVICES

-------------------------------------------------------------*/

/*GET FORMATED CLIENT/BEAM DATASET AND SELECT INPUTS THAT WE WILL NEED FOR ALL DATA SERVICES */

DATA DATA_SERVICES_INPUTS_MASTER;
	SET FORMAT_ACOUNT_EXTRACT_2;
	CUSTOMER_ACCOUNT = CLIENTACCOUNTID;
	FIRST_NAME = PFNAME;
	MIDDLE_NAME = PMIDDLE;
	LAST_NAME = PLNAME;
	SUFFIX = '';
	SSN = PSSN_SIN;
	ADDRESS_1 = _1STADDRESS1;
	ADDRESS_2 = _1STADDRESS2;
	CITY	  = _1STCITY;
	STATE     = _1STSTATE;
	ZIP		  = _1STZIPPOSTAL;
	AGREEMENT_DATE = ACCOUNTOPENDATE;
	DOB 	  = PBIRTHDATE;
	KEEP CUSTOMER_ACCOUNT FIRST_NAME MIDDLE_NAME LAST_NAME SUFFIX SSN ADDRESS_1 ADDRESS_2 CITY STATE ZIP AGREEMENT_DATE DOB;
RUN;


	/*MAKE DATA SERVICES INPUTS */

			/*LN_SCRA_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\LN_SCRA_INPUT.SAS";
			/*LNPER_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\LNPER_INPUT.SAS";
			/*LNPMTSCORE_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\LNPMTSCORE_INPUT.SAS";
			/*LNWATERFALL_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\LN_WATERFALL_INPUT.SAS";
			/*TLO_WATERFALL_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\TLO_WATERFALL_INPUT.SAS";

	/*ROLLUP / SEND OUT DATA SERVICE INPUTS*/

			/* ROLLUP AND SEND*/
				%INCLUDE "&WHEREPRGMSAT.\SEND OUT DATA SERVICE INPUTS.SAS";