/*--------------------FORMAT CLIENT_ACCOUNT_EXTRACT---------------

	1) STANDARDIZING SSN (TAKING OUT '-' ETC)
	2) STANDARDIZING DATES (REPLACING '-' WITH '/' ETC)

----------------------------------------------------------------*/

DATA FORMAT_ACOUNT_EXTRACT_1;
	SET ACOUNT_EXTRACT;
/*CHARACTER VARIABLES UPCASE / CHANGE MISSING VALUES TO '' */
	ARRAY VARS(*) _CHARACTER_;
		DO I=1 TO DIM(VARS);
			VARS(I) = UPCASE(VARS(I));
			IF VARS(I) = 'NA' 
			OR VARS(I) = '.' 
			OR VARS(I) = 'N/A' THEN VARS(I) = '';
		END;
		DROP I;
RUN;


DATA FORMAT_ACOUNT_EXTRACT_2;
	SET FORMAT_ACOUNT_EXTRACT_1;
/*	DATES*/
	CODATE = COMPRESS(TRANWRD(CODATE,'-','/'));
	ISSUERLPDATE = COMPRESS(TRANWRD(ISSUERLPDATE,'-','/'));
	ACCOUNTOPENDATE = COMPRESS(TRANWRD(ACCOUNTOPENDATE,'-','/'));
	DELINQUENCYDATE = COMPRESS(TRANWRD(DELINQUENCYDATE,'-','/'));
	SCHEDULEDREPORTDATE = COMPRESS(TRANWRD(SCHEDULEDREPORTDATE,'-','/'));
	DELETIONDATE = COMPRESS(TRANWRD(DELETIONDATE,'-','/'));
	LASTPAYDATE = COMPRESS(TRANWRD(LASTPAYDATE,'-','/'));
	PBIRTHDATE = COMPRESS(TRANWRD(PBIRTHDATE,'-','/'));
	SBIRTHDATE = COMPRESS(TRANWRD(SBIRTHDATE,'-','/'));
	EMPLOYMENT_START_DATE = COMPRESS(TRANWRD(EMPLOYMENT_START_DATE,'-','/'));
	EMPLOYMENT_END_DATE = COMPRESS(TRANWRD(EMPLOYMENT_END_DATE,'-','/'));
	ACCOUNTRECEIVEDATE = COMPRESS(TRANWRD(ACCOUNTRECEIVEDATE,'-','/'));
	ORIG_ACCOUNT_OPEN_DATE = COMPRESS(TRANWRD(ORIG_ACCOUNT_OPEN_DATE,'-','/'));
/*	SSN*/
	PSSN_SIN = COMPRESS(TRANWRD(PSSN_SIN,'-',''));
	SSSN_SIN = COMPRESS(TRANWRD(SSSN_SIN,'-',''));
/*PHONENBRS*/
	ORIGPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(ORIGPHONE,'(',''),')',''),'-',''));
	_1STPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_1STPHONE,'(',''),')',''),'-',''));
	_2NDPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_2NDPHONE,'(',''),')',''),'-',''));
	_3RDPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_3RDPHONE,'(',''),')',''),'-',''));
	_4THPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_4THPHONE,'(',''),')',''),'-',''));
	_5THPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_5THPHONE,'(',''),')',''),'-',''));
	_6THPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_6THPHONE,'(',''),')',''),'-',''));
	_7THPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_7THPHONE,'(',''),')',''),'-',''));
	_8THPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_8THPHONE,'(',''),')',''),'-',''));
	_9THPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_9THPHONE,'(',''),')',''),'-',''));
	_10THPHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(_10THPHONE,'(',''),')',''),'-',''));
	EMPLOYER_PHONE = COMPRESS(TRANWRD(TRANWRD(TRANWRD(EMPLOYER_PHONE,'(',''),')',''),'-',''));
/*MIGHT NEED TO ADD MORE TO THIS*/
RUN;






	



