OPTIONS NOXWAIT;

%LET TRIGGER = 1;

%MACRO DIRECTORIES(SHOULD_RUN=);

	%IF &SHOULD_RUN. = 1 %THEN 
		%DO;
			%SYSEXEC MKDIR "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\STANDARDIZED CLIENT FILES"
						   "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\CUSTOM PROPERTY INPUT\&DATE."
						   "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\EXCEPTION FILES\&DATE."
						   "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\EXPORT TO BEAM\&DATE."					
						   "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\DATA SERVICES INPUTS\&DATE."
/*						   "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\DATA SERVICES BACKUPS\&DATE.";*/

		%END;

%MEND;

%DIRECTORIES(SHOULD_RUN=&TRIGGER)