%MACRO ORGANIZE_IMPORT();

		%IF &TOTAL_COUNTER_USE.= 1   %THEN 
			%DO;	


				PROC IMPORT DATAFILE="&FILE_USE"
					OUT=IMPORTED_FILE_&TOTAL_COUNTER_USE
					DBMS=TAB
					REPLACE
					DELIMITER='09'X;
					GUESSINGROWS=2500;
				RUN;


				DATA IMPORTED_FILE_&TOTAL_COUNTER_USE;
					FORMAT 
						ACCOUNTID        
				        ISSUERNAME       
				        ISSUERACCOUNTNUMBER 
				        SELLERACCOUNTNUMBER 
				        PORTFOLIO        
				        CLIENTACCOUNTID 
				        OPENAMOUNT       
				        CODATE           
				        COAMOUNT         
				        ISSUERLPDATE     
				        ISSUERLPAMOUNT   
				        ACCOUNTOPENDATE  
				        CONTRACTINTERESTRATE 
				        ORIGPHONE       
				        ORIGADDRESS1     
				        ORIGADDRESS2     
				        ORIGCITY         
				        ORIGSTATE        
				        ORIGZIPPOSTAL   
				        ORIGPRODUCT      
				        ACCOUNTTYPE      
				        CURBALANCE       
				        ACQUISITIONBALANCE 
				        DELINQUENCYDATE  
				        ALTERNATIVEDATEOFDELINQUENCY 
				        SCHEDULEDREPORTDATE 
				        DELETIONDATE     
				        TOTALPAYMENTS    
				        LASTPAYDATE      
				        LASTPAYAMOUNT    
				        TOTAL_PAID_SINCE_CHARGED_OFF 
				        INBEAMNAME       
				        OUTBEAMNAME      
				        QUEUENAME        
				        AGENCY_DEBTBUYER 
				        STATUS           
				        FLEXTAG          
				        RATING          
				        RESTRICTION      
				        PFNAME           
				        PMIDDLE          
				        PLNAME           
				        PSSN_SIN         
				        PBIRTHDATE       
				        PEMAIL           
				        SFNAME           
				        SMIDDLE          
				        SLNAME           
				        SSSN_SIN         
				        SBIRTHDATE       
				        SEMAIL           
				        _1STADDRESSTYPE  
				        _1STADDRESS1     
				        _1STADDRESS2     
				        _1STCITY         
				        _1STSTATE        
				        _1STZIPPOSTAL    
				        _2NDADDRESSTYPE  
				        _2NDADDRESS1     
				        _2NDADDRESS2     
				        _2NDCITY         
				        _2NDSTATE        
				        _2NDZIPPOSTAL    
				        _3RDADDRESSTYPE  
				        _3RDADDRESS1     
				        _3RDADDRESS2     
				        _3RDCITY         
				        _3RDSTATE        
				        _3RDZIPPOSTAL    
				        _4THADDRESSTYPE  
				        _4THADDRESS1     
				        _4THADDRESS2     
				        _4THCITY        
				        _4THSTATE        
				        _4THZIPPOSTAL    
				        _5THADDRESSTYPE  
				        _5THADDRESS1     
				        _5THADDRESS2     
				        _5THCITY         
				        _5THSTATE        
				        _5THZIPPOSTAL    
				        _1STPHONETYPE    
				        _1STLINETYPE     
				        _1STPHONE        
				        _1STPHONESOURCE  
				        _1STPHONENOTE    
				        _1STPHONESTATUS  
				        _2NDPHONETYPE    
				        _2NDLINETYPE     
				        _2NDPHONE        
				        _2NDPHONESOURCE  
				        _2NDPHONENOTE    
				        _2NDPHONESTATUS  
				        _3RDPHONETYPE    
				        _3RDLINETYPE     
				        _3RDPHONE        
				        _3RDPHONESOURCE  
				        _3RDPHONENOTE    
				        _3RDPHONESTATUS  
				        _4THPHONETYPE    
				        _4THLINETYPE     
				        _4THPHONE        
				        _4THPHONESOURCE  
				        _4THPHONENOTE    
				        _4THPHONESTATUS  
				        _5THPHONETYPE    
				        _5THLINETYPE     
				        _5THPHONE        
				        _5THPHONESOURCE  
				        _5THPHONENOTE    
				        _5THPHONESTATUS  
				        _6THPHONETYPE    
				        _6THLINETYPE    
				        _6THPHONE        
				        _6THPHONESOURCE  
				        _6THPHONENOTE    
				        _6THPHONESTATUS 
				        _7THPHONETYPE    
				        _7THLINETYPE    
				        _7THPHONE        
				        _7THPHONESOURCE  
				        _7THPHONENOTE   
				        _7THPHONESTATUS  
				        _8THPHONETYPE    
				        _8THLINETYPE     
				        _8THPHONE        
				        _8THPHONESOURCE  
				        _8THPHONENOTE    
				        _8THPHONESTATUS  
				        _9THPHONETYPE    
				        _9THLINETYPE     
				        _9THPHONE        
				        _9THPHONESOURCE 
				        _9THPHONENOTE    
				        _9THPHONESTATUS  
				        _10THPHONETYPE   
				        _10THLINETYPE    
				        _10THPHONE       
				        _10THPHONESOURCE 
				        _10THPHONENOTE   
				        _10THPHONESTATUS 
				        EMPLOYER         
				        OCCUPATION       
				        EMPLOYER_ADDRESS_1 
				        EMPLOYER_ADDRESS_2 
				        EMPLOYER_CITY   
				        EMPLOYER_STATE   
				        EMPLOYER_ZIP     
				        EMPLOYER_PHONE   
				        SALARY          
				        PAY_BASIS       
				        EMPLOYMENT_START_DATE 
				        EMPLOYMENT_END_DATE 
				        COLLATERAL_TYPE  
				        CURRENT_VALUE    
				        REFERRAL_AMOUNT  
				        DESCRIPTION     
				        OWNER            
				        ACCOUNTRECEIVEDATE 
				        LOT              
				        HAS_MEDIA        
				        PRINCIPAL        
				        ORIG_ORIGINALCREDITORADDRESS 
				        ORIG_RECEIVED    
				        ORIG_CUSTOMER   
				        ORIG_VEH_DEALERCITY 
				        ORIG_VEH_DEALERNAME 
				        ORIG_VEH_DEALERSTATE 
				        ORIG_VEH_DEALERZIP 
				        ORIG_ENTITY      
				        ORIG_LOANAMT     
				        ORIG_ACCOUNT_OPEN_DATE 
				        ORIG_LOANPURPOSE 
				        ORIG_LOANTERM   
				        CP_DEBT_BUYER_ADDRESS__CA_REQUIR 
				        CP_LN_DATA       
				        SCORE            ;
					SET IMPORTED_FILE_&TOTAL_COUNTER_USE;
				RUN;

				PROC EXPORT DATA=IMPORTED_FILE_&TOTAL_COUNTER_USE
					OUTFILE=(CATX(''
							      ,'"'
								  ,E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\STANDARDIZED CLIENT FILES\
								  ,"&NEW_FILE_NAME_USE"
								  ,'_'
								  ,"&TOTAL_COUNTER_USE"
								  ,'.DLM'))

			%END;


		%IF &TOTAL_COUNTER_USE. ^= 1   %THEN 
			%DO;

				PROC IMPORT DATAFILE="&FILE_USE"
					OUT=IMPORTED_FILE_&TOTAL_COUNTER_USE
					DBMS=DLM
					REPLACE
					DELIMITER='09'X;
					GUESSINGROWS=2500;
				RUN;


				DATA IMPORTED_FILE_&TOTAL_COUNTER_USE;
					FORMAT ACCOUNTID        
				        ISSUERNAME       
				        ISSUERACCOUNTNUMBER 
				        SELLERACCOUNTNUMBER 
				        PORTFOLIO        
				        CLIENTACCOUNTID 
				        OPENAMOUNT       
				        CODATE           
				        COAMOUNT         
				        ISSUERLPDATE     
				        ISSUERLPAMOUNT   
				        ACCOUNTOPENDATE  
				        CONTRACTINTERESTRATE 
				        ORIGPHONE       
				        ORIGADDRESS1     
				        ORIGADDRESS2     
				        ORIGCITY         
				        ORIGSTATE        
				        ORIGZIPPOSTAL   
				        ORIGPRODUCT      
				        ACCOUNTTYPE      
				        CURBALANCE       
				        ACQUISITIONBALANCE 
				        DELINQUENCYDATE  
				        ALTERNATIVEDATEOFDELINQUENCY 
				        SCHEDULEDREPORTDATE 
				        DELETIONDATE     
				        TOTALPAYMENTS    
				        LASTPAYDATE      
				        LASTPAYAMOUNT    
				        TOTAL_PAID_SINCE_CHARGED_OFF 
				        INBEAMNAME       
				        OUTBEAMNAME      
				        QUEUENAME        
				        AGENCY_DEBTBUYER 
				        STATUS           
				        FLEXTAG          
				        RATING          
				        RESTRICTION      
				        PFNAME           
				        PMIDDLE          
				        PLNAME           
				        PSSN_SIN         
				        PBIRTHDATE       
				        PEMAIL           
				        SFNAME           
				        SMIDDLE          
				        SLNAME           
				        SSSN_SIN         
				        SBIRTHDATE       
				        SEMAIL           
				        _1STADDRESSTYPE  
				        _1STADDRESS1     
				        _1STADDRESS2     
				        _1STCITY         
				        _1STSTATE        
				        _1STZIPPOSTAL    
				        _2NDADDRESSTYPE  
				        _2NDADDRESS1     
				        _2NDADDRESS2     
				        _2NDCITY         
				        _2NDSTATE        
				        _2NDZIPPOSTAL    
				        _3RDADDRESSTYPE  
				        _3RDADDRESS1     
				        _3RDADDRESS2     
				        _3RDCITY         
				        _3RDSTATE        
				        _3RDZIPPOSTAL    
				        _4THADDRESSTYPE  
				        _4THADDRESS1     
				        _4THADDRESS2     
				        _4THCITY        
				        _4THSTATE        
				        _4THZIPPOSTAL    
				        _5THADDRESSTYPE  
				        _5THADDRESS1     
				        _5THADDRESS2     
				        _5THCITY         
				        _5THSTATE        
				        _5THZIPPOSTAL    
				        _1STPHONETYPE    
				        _1STLINETYPE     
				        _1STPHONE        
				        _1STPHONESOURCE  
				        _1STPHONENOTE    
				        _1STPHONESTATUS  
				        _2NDPHONETYPE    
				        _2NDLINETYPE     
				        _2NDPHONE        
				        _2NDPHONESOURCE  
				        _2NDPHONENOTE    
				        _2NDPHONESTATUS  
				        _3RDPHONETYPE    
				        _3RDLINETYPE     
				        _3RDPHONE        
				        _3RDPHONESOURCE  
				        _3RDPHONENOTE    
				        _3RDPHONESTATUS  
				        _4THPHONETYPE    
				        _4THLINETYPE     
				        _4THPHONE        
				        _4THPHONESOURCE  
				        _4THPHONENOTE    
				        _4THPHONESTATUS  
				        _5THPHONETYPE    
				        _5THLINETYPE     
				        _5THPHONE        
				        _5THPHONESOURCE  
				        _5THPHONENOTE    
				        _5THPHONESTATUS  
				        _6THPHONETYPE    
				        _6THLINETYPE    
				        _6THPHONE        
				        _6THPHONESOURCE  
				        _6THPHONENOTE    
				        _6THPHONESTATUS 
				        _7THPHONETYPE    
				        _7THLINETYPE    
				        _7THPHONE        
				        _7THPHONESOURCE  
				        _7THPHONENOTE   
				        _7THPHONESTATUS  
				        _8THPHONETYPE    
				        _8THLINETYPE     
				        _8THPHONE        
				        _8THPHONESOURCE  
				        _8THPHONENOTE    
				        _8THPHONESTATUS  
				        _9THPHONETYPE    
				        _9THLINETYPE     
				        _9THPHONE        
				        _9THPHONESOURCE 
				        _9THPHONENOTE    
				        _9THPHONESTATUS  
				        _10THPHONETYPE   
				        _10THLINETYPE    
				        _10THPHONE       
				        _10THPHONESOURCE 
				        _10THPHONENOTE   
				        _10THPHONESTATUS 
				        EMPLOYER         
				        OCCUPATION       
				        EMPLOYER_ADDRESS_1 
				        EMPLOYER_ADDRESS_2 
				        EMPLOYER_CITY   
				        EMPLOYER_STATE   
				        EMPLOYER_ZIP     
				        EMPLOYER_PHONE   
				        SALARY          
				        PAY_BASIS       
				        EMPLOYMENT_START_DATE 
				        EMPLOYMENT_END_DATE 
				        COLLATERAL_TYPE  
				        CURRENT_VALUE    
				        REFERRAL_AMOUNT  
				        DESCRIPTION     
				        OWNER            
				        ACCOUNTRECEIVEDATE 
				        LOT              
				        HAS_MEDIA        
				        PRINCIPAL        
				        ORIG_ORIGINALCREDITORADDRESS 
				        ORIG_RECEIVED    
				        ORIG_CUSTOMER   
				        ORIG_VEH_DEALERCITY 
				        ORIG_VEH_DEALERNAME 
				        ORIG_VEH_DEALERSTATE 
				        ORIG_VEH_DEALERZIP 
				        ORIG_ENTITY      
				        ORIG_LOANAMT     
				        ORIG_ACCOUNT_OPEN_DATE 
				        ORIG_LOANPURPOSE 
				        ORIG_LOANTERM   
				        CP_DEBT_BUYER_ADDRESS__CA_REQUIR 
				        CP_LN_DATA       
				        SCORE            ;
					SET IMPORTED_FILE_&TOTAL_COUNTER_USE;
				RUN;

				PROC EXPORT DATA=IMPORTED_FILE_&TOTAL_COUNTER_USE
					OUTFILE=(CATX(''
								  ,'"'
								  ,E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\STANDARDIZED CLIENT FILES\
								  ,"&NEW_FILE_NAME_USE"
								  ,'_'
								  ,"&TOTAL_COUNTER_USE"
								  ,'.DLM'))
					REPLACE
					DBMS=DLM
					DELIMITER='|';
				RUN;

			%END;

%MEND;