/*AT THIS POINT WE SHOULD HAVE 4 FILES

	1) BANKRUPTCY FILE
	2) LITIGIOUS FILE
	3) DECEASED
	4) MILITARY FILE					*/


/*NEED TO ROLLUP THESE FILES AND OUTPUT THEM*/

/*I MADE THIS DIRECTORY AT BEGINNING OF PROGRAM*/
%LET PATH = E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\EXCEPTION FILES\&DATE.;

/*BANKRUPTCY FILE*/
PROC EXPORT DATA=BANKRUPTCY_FINAL
	OUTFILE="&PATH.\BANKRUPTCY_FINAL_EXCEPTIONS.CSV"
	DBMS=CSV
	REPLACE
	LABEL;
RUN;

/*GET DECEASED FILE*/
PROC EXPORT DATA=DECEASED_FINAL
	OUTFILE="&PATH.\DECEASED_FINAL_EXCEPTIONS.CSV"
	DBMS=CSV
	REPLACE
	LABEL;
RUN;

/*GET LITIGIOUS FILE*/
PROC EXPORT DATA=LITIGIOUS_FINAL
	OUTFILE="&PATH.\LITIGIOUS_FINAL_EXCEPTIONS.CSV"
	DBMS=CSV
	REPLACE
	LABEL;
RUN;