/*FIRST WE NEED TO MAKE THE GENERAL SCRUB TEMPLATE*/

DATA SCRUB_TEMPLATE;
    LENGTH
        ACCOUNTID        $ 50
        ISSUERACCOUNTNUMBER  $ 50
        CLIENTACCOUNTID   $ 50
        SSN               $ 50
        FLEXTAG           $ 50
        EMAIL             $ 50
        NEWADDRESS1       $ 50
        NEWCITY1          $ 50
        NEWSTATE1         $ 50
        NEWZIP1           $ 50
        NEWADDRESS2       $ 50
        NEWCITY2          $ 50
        NEWSTATE2         $ 50
        NEWZIP2           $ 50
        NEWADDRESS3       $ 50
        NEWCITY3          $ 50
        NEWSTATE3         $ 50
        NEWZIP3           $ 50
        NEWADDRESS4       $ 50
        NEWCITY4          $ 50
        NEWSTATE4         $ 50
        NEWZIP4           $ 50
        NEWADDRESS5       $ 50
        NEWCITY5          $ 50
        NEWSTATE5         $ 50
        NEWZIP5           $ 50
        HOMEPHONE1        $ 50
        HOMEPHONE1LINETYPE  $ 50
        HOMEPHONE2        $ 50
        HOMEPHONE2LINETYPE  $ 50
        HOMEPHONE3        $ 50
        HOMEPHONE3LINETYPE  $ 50
        HOMEPHONE4        $ 50
        HOMEPHONE4LINETYPE  $ 50
        HOMEPHONE5        $ 50
        HOMEPHONE5LINETYPE  $ 50
        HOMEPHONE6        $ 50
        HOMEPHONE6LINETYPE  $ 50
        HOMEPHONE7        $ 50
        HOMEPHONE7LINETYPE  $ 50
        HOMEPHONE8        $ 50
        HOMEPHONE8LINETYPE  $ 50
        HOMEPHONE9        $ 50
        HOMEPHONE9LINETYPE  $ 50
        HOMEPHONE10       $ 50
        HOMEPHONE10LINETYPE  $ 50
        WORKPHONE1        $ 50
        WORKPHONE1LINETYPE  $ 50
        WORKPHONE2        $ 50
        WORKPHONE2LINETYPE  $ 50
        WORKPHONE3        $ 50
        WORKPHONE3LINETYPE  $ 50
        WORKPHONE4        $ 50
        WORKPHONE4LINETYPE  $ 50
        WORKPHONE5        $ 50
        WORKPHONE5LINETYPE  $ 50
        RELATIVEPHONE1    $ 50
        RELATIVEPHONE1LINETYPE  $ 50
        RELATIVEPHONE2    $ 50
        RELATIVEPHONE2LINETYPE  $ 50
        RELATIVEPHONE3    $ 50
        RELATIVEPHONE3LINETYPE  $ 50
        RELATIVEPHONE4    $ 50
        RELATIVEPHONE4LINETYPE  $ 50
        RELATIVEPHONE5    $ 50
        RELATIVEPHONE5LINETYPE  $ 50
        REFERENCEPHONE1   $ 50
        REFERENCEPHONE1LINETYPE  $ 50
        REFERENCEPHONE2   $ 50
        REFERENCEPHONE2LINETYPE  $ 50
        REFERENCEPHONE3   $ 50
        REFERENCEPHONE3LINETYPE  $ 50
        REFERENCEPHONE4   $ 50
        REFERENCEPHONE4LINETYPE  $ 50
        REFERENCEPHONE5   $ 50
        REFERENCEPHONE5LINETYPE  $ 50
        EMPLOYER_NAME     $ 50
        EMPLOYER_ADDRESS_1  $ 50
        EMPLOYER_ADDRESS_2  $ 50
        EMPLOYER_CITY     $ 50
        EMPLOYER_STATE    $ 50
        EMPLOYER_ZIP      $ 50
        EMPLOYER_PHONE    $ 50
        DATE_EMPLOYMENT_START  $ 50
        DATE_EMPLOYMENT_END  $ 50 ;
    FORMAT
        ACCOUNTID        $CHAR50.
        ISSUERACCOUNTNUMBER $CHAR50.
        CLIENTACCOUNTID  $CHAR50.
        SSN              $CHAR50.
        FLEXTAG         $CHAR50.
        EMAIL            $CHAR50.
        NEWADDRESS1     $CHAR50.
        NEWCITY1         $CHAR50.
        NEWSTATE1        $CHAR50.
        NEWZIP1          $CHAR50.
        NEWADDRESS2     $CHAR50.
        NEWCITY2         $CHAR50.
        NEWSTATE2        $CHAR50.
        NEWZIP2          $CHAR50.
        NEWADDRESS3      $CHAR50.
        NEWCITY3         $CHAR50.
        NEWSTATE3        $CHAR50.
        NEWZIP3          $CHAR50.
        NEWADDRESS4      $CHAR50.
        NEWCITY4         $CHAR50.
        NEWSTATE4        $CHAR50.
        NEWZIP4          $CHAR50.
        NEWADDRESS5      $CHAR50.
        NEWCITY5         $CHAR50.
        NEWSTATE5        $CHAR50.
        NEWZIP5          $CHAR50.
        HOMEPHONE1       $CHAR50.
        HOMEPHONE1LINETYPE $CHAR50.
        HOMEPHONE2       $CHAR50.
        HOMEPHONE2LINETYPE $CHAR50.
        HOMEPHONE3       $CHAR50.
        HOMEPHONE3LINETYPE $CHAR50.
        HOMEPHONE4       $CHAR50.
        HOMEPHONE4LINETYPE $CHAR50.
        HOMEPHONE5       $CHAR50.
        HOMEPHONE5LINETYPE $CHAR50.
        HOMEPHONE6       $CHAR50.
        HOMEPHONE6LINETYPE $CHAR50.
        HOMEPHONE7       $CHAR50.
        HOMEPHONE7LINETYPE $CHAR50.
        HOMEPHONE8       $CHAR50.
        HOMEPHONE8LINETYPE $CHAR50.
        HOMEPHONE9       $CHAR50.
        HOMEPHONE9LINETYPE $CHAR50.
        HOMEPHONE10      $CHAR50.
        HOMEPHONE10LINETYPE $CHAR50.
        WORKPHONE1       $CHAR50.
        WORKPHONE1LINETYPE $CHAR50.
        WORKPHONE2       $CHAR50.
        WORKPHONE2LINETYPE $CHAR50.
        WORKPHONE3       $CHAR50.
        WORKPHONE3LINETYPE $CHAR50.
        WORKPHONE4       $CHAR50.
        WORKPHONE4LINETYPE $CHAR50.
        WORKPHONE5       $CHAR50.
        WORKPHONE5LINETYPE $CHAR50.
        RELATIVEPHONE1   $CHAR50.
        RELATIVEPHONE1LINETYPE $CHAR50.
        RELATIVEPHONE2   $CHAR50.
        RELATIVEPHONE2LINETYPE $CHAR50.
        RELATIVEPHONE3   $CHAR50.
        RELATIVEPHONE3LINETYPE $CHAR50.
        RELATIVEPHONE4   $CHAR50.
        RELATIVEPHONE4LINETYPE $CHAR50.
        RELATIVEPHONE5   $CHAR50.
        RELATIVEPHONE5LINETYPE $CHAR50.
        REFERENCEPHONE1  $CHAR50.
        REFERENCEPHONE1LINETYPE $CHAR50.
        REFERENCEPHONE2  $CHAR50.
        REFERENCEPHONE2LINETYPE $CHAR50.
        REFERENCEPHONE3  $CHAR50.
        REFERENCEPHONE3LINETYPE $CHAR50.
        REFERENCEPHONE4  $CHAR50.
        REFERENCEPHONE4LINETYPE $CHAR50.
        REFERENCEPHONE5  $CHAR50.
        REFERENCEPHONE5LINETYPE $CHAR50.
        EMPLOYER_NAME    $CHAR50.
        EMPLOYER_ADDRESS_1 $CHAR50.
        EMPLOYER_ADDRESS_2 $CHAR50.
        EMPLOYER_CITY    $CHAR50.
        EMPLOYER_STATE   $CHAR50.
        EMPLOYER_ZIP     $CHAR50.
        EMPLOYER_PHONE   $CHAR50.
        DATE_EMPLOYMENT_START $CHAR50.
        DATE_EMPLOYMENT_END $CHAR50. ;
RUN;


/*WE NEED TO LOAD TLO WATERFALL DATA AND GET PHONE INFORMATION*/

DATA TLO_PHONE_SCRUB_PRE;
	SET TLO_WATERFALL_INPUT_EBG;
	KEEP	CUSTOMER_ACCOUNT
			ADDRESS_1
			ADDRESS_2
			CITY
			ZIP
			FIRST_NAME
			LAST_NAME
			MIDDLE_NAME
			SSN
			STATE
			TLOADDRESS1CITY
			TLOADDRESS1COUNTY
			TLOADDRESS1DATEFIRSTSEEN
			TLOADDRESS1DATELASTSEEN
			TLOADDRESS1LINE1
			TLOADDRESS1LINE2
			TLOADDRESS1LINE3
			TLOADDRESS1STATE
			TLOADDRESS1ZIP
			TLOADDRESS2CITY
			TLOADDRESS2COUNTY
			TLOADDRESS2DATEFIRSTSEEN
			TLOADDRESS2DATELASTSEEN
			TLOADDRESS2LINE1
			TLOADDRESS2LINE2
			TLOADDRESS2LINE3
			TLOADDRESS2STATE
			TLOADDRESS2ZIP
			TLOPHONE1
			TLOPHONE2
			TLOPHONE3
			TLOPHONE1PHONETYPE
			TLOPHONE1SCORE
			TLOPHONE2PHONETYPE
			TLOPHONE2SCORE
			TLOPHONE3PHONETYPE
			TLOPHONE3SCORE;
RUN;

