/*------------------------------------------------------------------------------

	AUTHOR: JUSTIN HUBBARD, EMERGENT BUSINESS GROUP

	PURPOSE: AUTOMATION OF EBG CLIENT/BEAM PORTFOLIO IMPORT AND DATA SERVICES ECOSYSTEM
	STEPS: 

		1) IMPORT FILES AND STANDARDIZE IMPORTED COLUMNS
			* BEAM IMPORTS WILL BE CONSTANT EVERY TIME (POS/CRM SOFTWARE THAT EMERGENT GROUP USES)
		    * IMPORTING RAW DATA FROM CLIENTS WILL BE STANDARDIZED BY JOHN THEN IMPORTED INTO A TEMPLATE I CREATE.
		2) USE STANDARDIZED FILE FROM STEP 1 OF MY PROCESS TO THEN CREATE DATA SERVICES INPUTS
			* A DIRECTORY FOR THE DATE OF THE RUN WILL BE CREATED IN A DATA SERVICES INPUT AND DATA SERVICES OUTPUT FOLDER TO EASILY KEEP TRACK OF DATA SERVICES DATA
		3) PROCESS WILL THEN LOOP UNTIL DATA IS FOUND IN THE DATA SERVICES OUTPUT FOLDER (RESULTS FROM DATA SERVICES INPUTS). ONCE RESULTS ARE FOUND THE PROCESS
		   WILL CONTINUE TO STEP 4 (IN PROGRESS)
		

--------------------------------------------------------------------------------*/

OPTIONS SYMBOLGEN MPRINT MLOGIC;

%LET DATE=%SYSFUNC(INTNX(DAY,%SYSFUNC(TODAY()),0,END),DATE7.);
%PUT &DATE;

%PUT &SYSUSERID;

%GLOBAL DIRECTORIES;
%GLOBAL DATE;


%LET WHEREPRGMSAT = E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PROGRAMS\PROGRAMS;

/*TYPE CAN EITHER BE*/
/*	1) RAW (COMING FROM CLIENTS (NOT LOADED INTO BEAM YET))*/
/*	2) LOADED INTO BEAM (CAN USE BEAM IMPORT PROGRAM INSTEAD OF RAW CLIENT IMPORT)*/


%LET TYPE = %UPCASE(&TYPE1.);


%MACRO FILE_STANDARDIZATION_DECISION(TYPE=);

		/*	MAKE DIRECTORIES*/
			%INCLUDE "&WHEREPRGMSAT.\MAKE DIRECTORIES.SAS";

		/*KICK OFF PROCESS TO IMPORT CLIENT FILES*/
			%IF &TYPE = CLIENT %THEN
				%DO;
					%INCLUDE "&WHEREPRGMSAT.\IMPORT CLIENT DRIVER.SAS";
					%INCLUDE "&WHEREPRGMSAT.\FORMAT IMPORT.SAS";
					%INCLUDE "&WHEREPRGMSAT.\EXPORT TO BEAM.SAS";
					%INCLUDE "&WHEREPRGMSAT.\DATA SERVICES TREE.SAS";
				%END;

%MEND;

%FILE_STANDARDIZATION_DECISION(TYPE=&TYPE)




 






