/*NEED TO MAKE THE CUSTOM PROPERTY TEMPLATE WITH THE LN DATA SCORE */


/*MAKE CUSTOM PROPERTY TEMPLATE*/

PROC SQL;
	CREATE TABLE CUSTOM_PROPERTY_TEMPLATE_PRE AS
	SELECT A.ACCOUNTID							AS ACCOUNTID
		  ,A.CLIENTACCOUNTID
		  ,B.PAYMENTSCORE						AS LN_DATA
		  ,A.CP_DEBT_BUYER_ADDRESS__CA_REQUIR LABEL='Debt Buyer Address (CA Requirement)'
	FROM BEAM_ACCT_EXTRACT A
	RIGHT JOIN LNPMTSCORE_INPUT_EBG B
		ON (B.CUSTOMER_ACCOUNT = A.ISSUERACCOUNTNUMBER)
;
QUIT;

/*%LET CUSTOM_PROPERTY_PATH = &MASTER_DIR.\CUSTOM PROPERTY INPUT\&DATE.;*/

PROC EXPORT DATA=CUSTOM_PROPERTY_TEMPLATE_PRE
	OUTFILE="&CUSTOM_PROPERTY_PATH\CUSTOM_PROPERTY_INPUT.XLSX"
	REPLACE
	DBMS=XLSX;
RUN;

