/*-----------------------------------------------------------

	DATA SERVICES INPUT TREE

	AUTHOR: JUSTIN HUBBARD

	GOAL: SPLIT UP IMPORTED CLIENT DATA INTO ACCEPTABLE FORMATED DATASETS TO THEN SEND OUT TO DATA SERVICES

-------------------------------------------------------------*/

/*GET FORMATED CLIENT/BEAM DATASET AND SELECT INPUTS THAT WE WILL NEED FOR ALL DATA SERVICES */

DATA DATA_SERVICES_INPUTS_MASTER;
	Format Customer_Account First_name Middle_Name Last_Name Suffix SSN Address_1 Address_2
		City State Zip Agreement_Date DOB;
	SET FORMAT_ACOUNT_EXTRACT_2;
	CUSTOMER_ACCOUNT = ISSUER_ACCOUNT_NUMBER;
	FIRST_NAME = FIRST_NAME;
	MIDDLE_NAME = MIDDLE_NAME;
	LAST_NAME = LAST_NAME;
	SUFFIX = SUFFIX;
	SSN = SSN_SIN;
	ADDRESS_1 = ORIGINAL_ADDRESSL;
	ADDRESS_2 = ORIGINAL_ADDRESS2;
	CITY	  = ORIGINAL_CITY;
	STATE     = ORIGINAL_STATE;
	ZIP		  = ORIGINAL_ZIP_POSTAL_CODE;
	AGREEMENT_DATE = ACCOUNT_OPEN_DATE;
	DOB 	  = BIRTHDATE;
	KEEP CUSTOMER_ACCOUNT FIRST_NAME MIDDLE_NAME LAST_NAME SUFFIX SSN ADDRESS_1 ADDRESS_2 CITY STATE ZIP AGREEMENT_DATE DOB;
RUN;


	/*MAKE DATA SERVICES INPUTS */

			/*LN_SCRA_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\LN_SCRA_INPUT.SAS";
			/*LNPER_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\LNPER_INPUT.SAS";
			/*LNPMTSCORE_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\LNPMTSCORE_INPUT.SAS";
			/*LNWATERFALL_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\LN_WATERFALL_INPUT.SAS";
			/*TLO_WATERFALL_INPUT*/
				%INCLUDE "&WHEREPRGMSAT.\TLO_WATERFALL_INPUT.SAS";

	/*ROLLUP / SEND OUT DATA SERVICE INPUTS*/

			/* ROLLUP AND SEND*/
				%INCLUDE "&WHEREPRGMSAT.\SEND OUT DATA SERVICE INPUTS.SAS";