/*MAKE FILE THAT CAN BE IMPORTED INTO BEAM*/

/*%LET BEAM_EXPORT_PATH = E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\EXPORT TO BEAM\&DATE.\;*/

%LET EXPORT_TO_BEAM = EXPORT_TO_BEAM;

/*GET FULLPATH MACROS*/
%LET FULLPATH_EXPORT_TO_BEAM = &BEAM_EXPORT_PATH.&EXPORT_TO_BEAM._&DATE..CSV;


/*MAKE DATASET AVAILABLE FOR BEAM*/
PROC EXPORT
	DATA=FORMAT_ACOUNT_EXTRACT_2
	FILE="&FULLPATH_EXPORT_TO_BEAM"
	DBMS=CSV
	REPLACE;
RUN;

/*EMAIL WHEN FINISHED*/
/*OPTIONS EMAILSYS=SMTP EMAILHOST=MAIL.EBG.NET EMAILPORT=25;*/
/*FILENAME MYMAIL EMAIL; */
/*DATA _NULL_;*/
/*   FILE MYMAIL*/
/*		TO=('JLODMELL@EBG.NET')*/
/*	    FROM='PORTFOLIO_DATA@COMPLETE.COM'*/
/*        SUBJECT="PORTFOLIO DATA IS READY FOR BEAM - &DATE";*/
/*RUN;*/