/*--------------------FORMAT CLIENT_ACCOUNT_EXTRACT---------------

	1) STANDARDIZING SSN (TAKING OUT '-' ETC)
	2) STANDARDIZING DATES (REPLACING '-' WITH '/' ETC)

----------------------------------------------------------------*/

DATA FORMAT_ACOUNT_EXTRACT_1;
	SET ACOUNT_EXTRACT;
/*CHARACTER VARIABLES UPCASE / CHANGE MISSING VALUES TO '' */
	ARRAY VARS(*) _CHARACTER_;
		DO I=1 TO DIM(VARS);
			VARS(I) = UPCASE(VARS(I));
			IF VARS(I) = 'NA' 
			OR VARS(I) = '.' 
			OR VARS(I) = 'N/A'
			OR VARS(I) = 'N\A' THEN VARS(I) = '';
		END;
		DROP I;
RUN;


DATA FORMAT_ACOUNT_EXTRACT_2;
	SET FORMAT_ACOUNT_EXTRACT_1;
/*	DATES*/
	CODATE = COMPRESS(TRANWRD(CODATE,'-','/'));
	ISSUERLPDATE = COMPRESS(TRANWRD(ISSUERLPDATE,'-','/'));
	ACCOUNTOPENDATE = COMPRESS(TRANWRD(ACCOUNTOPENDATE,'-','/'));
	DELINQUENCYDATE = COMPRESS(TRANWRD(DELINQUENCYDATE,'-','/'));
	SCHEDULEDREPORTDATE = COMPRESS(TRANWRD(SCHEDULEDREPORTDATE,'-','/'));
	DELETIONDATE = COMPRESS(TRANWRD(DELETIONDATE,'-','/'));
	LASTPAYDATE = COMPRESS(TRANWRD(LASTPAYDATE,'-','/'));
	PBIRTHDATE = COMPRESS(TRANWRD(PBIRTHDATE,'-','/'));
	SBIRTHDATE = COMPRESS(TRANWRD(SBIRTHDATE,'-','/'));
	EMPLOYMENT_START_DATE = COMPRESS(TRANWRD(EMPLOYMENT_START_DATE,'-','/'));
	EMPLOYMENT_END_DATE = COMPRESS(TRANWRD(EMPLOYMENT_END_DATE,'-','/'));
	ACCOUNTRECEIVEDATE = COMPRESS(TRANWRD(ACCOUNTRECEIVEDATE,'-','/'));
	ORIG_ACCOUNT_OPEN_DATE = COMPRESS(TRANWRD(ORIG_ACCOUNT_OPEN_DATE,'-','/'));
/*	SSN*/
	PSSN_SIN = COMPRESS(PSSN_SIN,"1234567890","kis");
	SSSN_SIN = COMPRESS(SSSN_SIN,"1234567890","kis");
/*PHONENBRS*/
	ORIGPHONE = COMPRESS(COMPRESS(ORIGPHONE,"ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890","kis"));
	_1STPHONE = COMPRESS(COMPRESS(_1STPHONE,"ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890","kis"));
	_2NDPHONE = COMPRESS(COMPRESS(_2NDPHONE,"ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890","kis"));
	EMPLOYER_PHONE = COMPRESS(COMPRESS(EMPLOYER_PHONE,"ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890","kis"));
/*MIGHT NEED TO ADD MORE TO THIS*/
RUN;	



