%MACRO IMPORT_TLO();
		DATA TLO_WATERFALL_INPUT_EBG;
		    LENGTH
		        CUSTOMER_ACCOUNT $ 50
		        FIRST_NAME       $ 50
		        MIDDLE_NAME      $ 50
		        LAST_NAME        $ 50
		        SUFFIX           $ 50
		        SSN              $ 50
		        ADDRESS_1        $ 50
		        ADDRESS_2        $ 50
		        CITY             $ 50
		        STATE            $ 50
		        ZIP               $ 50
		        TLODATEOFDEATH    $ 50
		        TLOBANKRUPTCYMATCHCODES $ 50
		        TLOBANKRUPTCYCHAPTER   $ 50
		        TLOBANKRUPTCYDEBTORNAME $ 50
		        TLOBANKRUPTCYCASENUMBER   $ 50
		        TLOBANKRUPTCYFILEDATE   $ 50
		        TLOBANKRUPTCYDISCHARGEDATE $ 50
		        TLOBANKRUPTCYCLOSEDDATE $ 50
		        TLOBANKRUPTCYNOTICETYPE $ 50
		        TLOBANKRUPTCYATTORNEYNAME $ 50
		        TLOBANKRUPTCYATTORNEYADDRESS $ 50
		        TLOBANKRUPTCYATTORNEYADDRESSLINE $ 50
		        TLOBANKRUPTCYATTORNEYADDRES_0001 $ 50
		        TLOBANKRUPTCYATTORNEYADDRES_0002 $ 50
		        TLOBANKRUPTCYATTORNEYADDRESSCITY $ 50
		        TLOBANKRUPTCYATTORNEYADDRESSSTAT $ 50
		        TLOBANKRUPTCYATTORNEYADDRESSZIP $ 50
		        TLOBANKRUPTCYATTORNEYADDRESSZIP4 $ 50
		        TLOBANKRUPTCYATTORNEYPHONE $ 50
		        TLOBANKRUPTCYCOURTDISTRICT $ 50
		        TLOBANKRUPTCYCOURTDIVISION  $ 50
		        TLOBANKRUPTCYCOURTADDRESS $ 50
		        TLOBANKRUPTCYCOURTADDRESSLINE1 $ 50
		        TLOBANKRUPTCYCOURTADDRESSLINE2 $ 50
		        TLOBANKRUPTCYCOURTADDRESSLINE3 $ 50
		        TLOBANKRUPTCYCOURTADDRESSCITY $ 50
		        TLOBANKRUPTCYCOURTADDRESSSTATE $ 50
		        TLOBANKRUPTCYCOURTADDRESSZIP   $ 50
		        TLOBANKRUPTCYCOURTADDRESSZIP4 $ 50
		        TLOBANKRUPTCYCOURTPHONE  $ 50
		        TLOBANKRUPTCYTRUSTEENAME $ 50
		        TLOBANKRUPTCYTRUSTEEADDRESS $ 50
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE1 $ 50
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE2 $ 50
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE3 $ 50
		        TLOBANKRUPTCYTRUSTEEADDRESSCITY $ 50
		        TLOBANKRUPTCYTRUSTEEADDRESSSTATE $ 50
		        TLOBANKRUPTCYTRUSTEEADDRESSZIP  $ 50
		        TLOBANKRUPTCYTRUSTEEADDRESSZIP4  $ 50
		        TLOBANKRUPTCYTRUSTEEPHONE  $ 50
		        TLOBANKRUPTCYDISMISSEDDATE  $ 50
		        TLOBANKRUPTCYTRANSFERREDDATE $ 50
		        TLOBANKRUPTCYPLACEHOLDER $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORFULLNA $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORFIRSTN $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORLASTNA $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORMIDDLE $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORNAMESU $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORFULLAD $ 100
		        TLOBANKRUPTCYPRIMARYDEBTORADDRES $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORA_0001 $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORA_0002 $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORA_0003 $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORA_0004 $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORA_0005 $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORA_0006  $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORPHONE  $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORSSN   $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORAKA1 $ 50
		        TLOBANKRUPTCYPRIMARYDEBTORAKA2 $ 50
		        TLOBANKRUPTCYSECONDARYDEBTORFULL $ 50
		        TLOBANKRUPTCYSECONDARYDEBTORFIRS $ 50
		        TLOBANKRUPTCYSECONDARYDEBTORLAST $ 50
		        TLOBANKRUPTCYSECONDARYDEBTORMIDD $ 50
		        TLOBANKRUPTCYSECONDARYDEBTORNAME $ 50
		        TLOBANKRUPTCYSECONDARYDEBTO_0001 $ 100
		        TLOBANKRUPTCYSECONDARYDEBTORADDR $ 50
		        TLOBANKRUPTCYSECONDARYDEBTO_0002 $ 50
		        TLOBANKRUPTCYSECONDARYDEBTO_0003 $ 50
		        TLOBANKRUPTCYSECONDARYDEBTO_0004 $ 50
		        TLOBANKRUPTCYSECONDARYDEBTO_0005 $ 50
		        TLOBANKRUPTCYSECONDARYDEBTO_0006  $ 50
		        TLOBANKRUPTCYSECONDARYDEBTO_0007   $ 50
		        TLOBANKRUPTCYSECONDARYDEBTORPHON   $ 50
		        TLOBANKRUPTCYSECONDARYDEBTORSSN   $ 50
		        TLOBANKRUPTCYSECONDARYDEBTORAKA1 $ 50
		        TLOBANKRUPTCYSECONDARYDEBTORAKA2 $ 50
		        TLOBANKRUPTCYFLAG $ 50
		        TLOBANKRUPTCY341DATE   $ 50
		        TLOBANKRUPTCY341TIME  $ 50
		        TLOBANKRUPTCY341ADDRESSLINE1 $ 50
		        TLOBANKRUPTCY341ADDRESSLINE2 $ 50
		        TLOBANKRUPTCY341ADDRESSLINE3 $ 50
		        TLOBANKRUPTCY341ADDRESSCITY $ 50
		        TLOBANKRUPTCY341ADDRESSSTATE $ 50
		        TLOBANKRUPTCY341ADDRESSZIP $ 50
		        TLOBANKRUPTCY341ADDRESSZIP4 $ 50
		        TLOBANKRUPTCY341FULLADDRESS $ 50
		        TLOBANKRUPTCYVOLUNTARYFLAG $ 50
		        TLOBANKRUPTCYASSETSINDICATOR $ 50
		        TLOBANKRUPTCYORIGINALCHAPTER $ 50
		        TLOBANKRUPTCYCONVERTEDCHAPTER  $ 50
		        TLOBANKRUPTCYUPDATEDDATE   $ 50
		        TLOBANKRUPTCYTRUSTEEFIRSTNAME $ 50
		        TLOBANKRUPTCYTRUSTEEMIDDLENAME $ 50
		        TLOBANKRUPTCYTRUSTEELASTNAME $ 50
		        TLOBANKRUPTCYTRUSTEENAMESUFFIX $ 50
		        TLOBANKRUPTCYJUDGEINITIALS $ 50
		        TLOBANKRUPTCYCOURTNAME $ 50
		        TLOBANKRUPTCYATTORNEYFIRSTNAME $ 50
		        TLOBANKRUPTCYATTORNEYMIDDLENAME $ 50
		        TLOBANKRUPTCYATTORNEYLASTNAME $ 50
		        TLOBANKRUPTCYATTORNEYNAMESUFFIX $ 50
		        TLOBANKRUPTCYPROSEINDICATOR $ 50
		        TLOBANKRUPTCYLAWFIRM $ 50
		        TLOBANKRUPTCYBARDATE  $ 50
		        TLOADDRESS1LINE1 $ 50
		        TLOADDRESS1LINE2 $ 50
		        TLOADDRESS1LINE3 $ 50
		        TLOADDRESS1CITY  $ 50
		        TLOADDRESS1STATE $ 50
		        TLOADDRESS1ZIP    $ 50
		        TLOADDRESS1COUNTY $ 50
		        TLOADDRESS1DATEFIRSTSEEN  $ 50
		        TLOADDRESS1DATELASTSEEN   $ 50
		        TLOADDRESS2LINE1 $ 50
		        TLOADDRESS2LINE2 $ 50
		        TLOADDRESS2LINE3 $ 50
		        TLOADDRESS2CITY  $ 50
		        TLOADDRESS2STATE $ 50
		        TLOADDRESS2ZIP     $ 50
		        TLOADDRESS2COUNTY $ 50
		        TLOADDRESS2DATEFIRSTSEEN   $ 50
		        TLOADDRESS2DATELASTSEEN  $ 50
		        TLOPHONE1          $ 50
		        TLOPHONE1PHONETYPE $ 50
		        TLOPHONE1SCORE     $ 50
		        TLOPHONE2          $ 50
		        TLOPHONE2PHONETYPE $ 50
		        TLOPHONE2SCORE     $ 50
		        TLOPHONE3          $ 50
		        TLOPHONE3PHONETYPE $ 50
		        TLOPHONE3SCORE     $ 50
		        MATCHCODES       $ 50
		        BOB_TOOMANYHITS  $ 50 ;
		    LABEL
		        TLOBANKRUPTCYATTORNEYADDRESSLINE = "TLOBANKRUPTCYATTORNEYADDRESSLINE1"
		        TLOBANKRUPTCYATTORNEYADDRES_0001 = "TLOBANKRUPTCYATTORNEYADDRESSLINE2"
		        TLOBANKRUPTCYATTORNEYADDRES_0002 = "TLOBANKRUPTCYATTORNEYADDRESSLINE3"
		        TLOBANKRUPTCYATTORNEYADDRESSSTAT = "TLOBANKRUPTCYATTORNEYADDRESSSTATE"
		        TLOBANKRUPTCYPRIMARYDEBTORFULLNA = "TLOBANKRUPTCYPRIMARYDEBTORFULLNAME"
		        TLOBANKRUPTCYPRIMARYDEBTORFIRSTN = "TLOBANKRUPTCYPRIMARYDEBTORFIRSTNAME"
		        TLOBANKRUPTCYPRIMARYDEBTORLASTNA = "TLOBANKRUPTCYPRIMARYDEBTORLASTNAME"
		        TLOBANKRUPTCYPRIMARYDEBTORMIDDLE = "TLOBANKRUPTCYPRIMARYDEBTORMIDDLENAME"
		        TLOBANKRUPTCYPRIMARYDEBTORNAMESU = "TLOBANKRUPTCYPRIMARYDEBTORNAMESUFFIX"
		        TLOBANKRUPTCYPRIMARYDEBTORFULLAD = "TLOBANKRUPTCYPRIMARYDEBTORFULLADDRESS"
		        TLOBANKRUPTCYPRIMARYDEBTORADDRES = "TLOBANKRUPTCYPRIMARYDEBTORADDRESSLINE1"
		        TLOBANKRUPTCYPRIMARYDEBTORA_0001 = "TLOBANKRUPTCYPRIMARYDEBTORADDRESSLINE2"
		        TLOBANKRUPTCYPRIMARYDEBTORA_0002 = "TLOBANKRUPTCYPRIMARYDEBTORADDRESSLINE3"
		        TLOBANKRUPTCYPRIMARYDEBTORA_0003 = "TLOBANKRUPTCYPRIMARYDEBTORADDRESSCITY"
		        TLOBANKRUPTCYPRIMARYDEBTORA_0004 = "TLOBANKRUPTCYPRIMARYDEBTORADDRESSSTATE"
		        TLOBANKRUPTCYPRIMARYDEBTORA_0005 = "TLOBANKRUPTCYPRIMARYDEBTORADDRESSZIP"
		        TLOBANKRUPTCYPRIMARYDEBTORA_0006 = "TLOBANKRUPTCYPRIMARYDEBTORADDRESSZIP4"
		        TLOBANKRUPTCYSECONDARYDEBTORFULL = "TLOBANKRUPTCYSECONDARYDEBTORFULLNAME"
		        TLOBANKRUPTCYSECONDARYDEBTORFIRS = "TLOBANKRUPTCYSECONDARYDEBTORFIRSTNAME"
		        TLOBANKRUPTCYSECONDARYDEBTORLAST = "TLOBANKRUPTCYSECONDARYDEBTORLASTNAME"
		        TLOBANKRUPTCYSECONDARYDEBTORMIDD = "TLOBANKRUPTCYSECONDARYDEBTORMIDDLENAME"
		        TLOBANKRUPTCYSECONDARYDEBTORNAME = "TLOBANKRUPTCYSECONDARYDEBTORNAMESUFFIX"
		        TLOBANKRUPTCYSECONDARYDEBTO_0001 = "TLOBANKRUPTCYSECONDARYDEBTORFULLADDRESS"
		        TLOBANKRUPTCYSECONDARYDEBTORADDR = "TLOBANKRUPTCYSECONDARYDEBTORADDRESSLINE1"
		        TLOBANKRUPTCYSECONDARYDEBTO_0002 = "TLOBANKRUPTCYSECONDARYDEBTORADDRESSLINE2"
		        TLOBANKRUPTCYSECONDARYDEBTO_0003 = "TLOBANKRUPTCYSECONDARYDEBTORADDRESSLINE3"
		        TLOBANKRUPTCYSECONDARYDEBTO_0004 = "TLOBANKRUPTCYSECONDARYDEBTORADDRESSCITY"
		        TLOBANKRUPTCYSECONDARYDEBTO_0005 = "TLOBANKRUPTCYSECONDARYDEBTORADDRESSSTATE"
		        TLOBANKRUPTCYSECONDARYDEBTO_0006 = "TLOBANKRUPTCYSECONDARYDEBTORADDRESSZIP"
		        TLOBANKRUPTCYSECONDARYDEBTO_0007 = "TLOBANKRUPTCYSECONDARYDEBTORADDRESSZIP4"
		        TLOBANKRUPTCYSECONDARYDEBTORPHON = "TLOBANKRUPTCYSECONDARYDEBTORPHONE" ;
		    FORMAT
		        CUSTOMER_ACCOUNT $CHAR50.
		        FIRST_NAME       $CHAR50.
		        MIDDLE_NAME      $CHAR50.
		        LAST_NAME        $CHAR50.
		        SUFFIX           $CHAR50.
		        SSN              $CHAR50.
		        ADDRESS_1        $CHAR50.
		        ADDRESS_2       $CHAR50.
		        CITY             $CHAR50.
		        STATE            $CHAR50.
		        ZIP              $CHAR50.
		        TLODATEOFDEATH   $CHAR50.
		        TLOBANKRUPTCYMATCHCODES $CHAR50.
		        TLOBANKRUPTCYCHAPTER $CHAR50.
		        TLOBANKRUPTCYDEBTORNAME $CHAR50.
		        TLOBANKRUPTCYCASENUMBER $CHAR50.
		        TLOBANKRUPTCYFILEDATE $CHAR50.
		        TLOBANKRUPTCYDISCHARGEDATE $CHAR50.
		        TLOBANKRUPTCYCLOSEDDATE $CHAR50.
		        TLOBANKRUPTCYNOTICETYPE $CHAR50.
		        TLOBANKRUPTCYATTORNEYNAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESS $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSLINE $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRES_0001 $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRES_0002 $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSCITY $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSSTAT $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSZIP $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSZIP4 $CHAR50.
		        TLOBANKRUPTCYATTORNEYPHONE $CHAR50.
		        TLOBANKRUPTCYCOURTDISTRICT $CHAR50.
		        TLOBANKRUPTCYCOURTDIVISION $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESS $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSLINE1 $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSLINE2 $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSLINE3 $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSCITY $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSSTATE $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSZIP $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSZIP4 $CHAR50.
		        TLOBANKRUPTCYCOURTPHONE $CHAR50.
		        TLOBANKRUPTCYTRUSTEENAME $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESS $CHAR100.
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE1 $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE2 $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE3 $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSCITY $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSSTATE $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSZIP $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSZIP4 $CHAR50.
		        TLOBANKRUPTCYTRUSTEEPHONE $CHAR50.
		        TLOBANKRUPTCYDISMISSEDDATE $CHAR50.
		        TLOBANKRUPTCYTRANSFERREDDATE $CHAR50.
		        TLOBANKRUPTCYPLACEHOLDER $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORFULLNA $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORFIRSTN $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORLASTNA $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORMIDDLE $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORNAMESU $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORFULLAD $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORADDRES $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0001 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0002 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0003 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0004 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0005 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0006 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORPHONE $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORSSN $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORAKA1 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORAKA2 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORFULL $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORFIRS $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORLAST $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORMIDD $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORNAME $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0001 $CHAR100.
		        TLOBANKRUPTCYSECONDARYDEBTORADDR $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0002 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0003 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0004 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0005 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0006 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0007 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORPHON $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORSSN $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORAKA1 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORAKA2 $CHAR50.
		        TLOBANKRUPTCYFLAG $CHAR50.
		        TLOBANKRUPTCY341DATE $CHAR50.
		        TLOBANKRUPTCY341TIME $CHAR50.
		        TLOBANKRUPTCY341ADDRESSLINE1 $CHAR50.
		        TLOBANKRUPTCY341ADDRESSLINE2 $CHAR50.
		        TLOBANKRUPTCY341ADDRESSLINE3 $CHAR50.
		        TLOBANKRUPTCY341ADDRESSCITY $CHAR50.
		        TLOBANKRUPTCY341ADDRESSSTATE $CHAR50.
		        TLOBANKRUPTCY341ADDRESSZIP $CHAR50.
		        TLOBANKRUPTCY341ADDRESSZIP4 $CHAR50.
		        TLOBANKRUPTCY341FULLADDRESS $CHAR50.
		        TLOBANKRUPTCYVOLUNTARYFLAG $CHAR50.
		        TLOBANKRUPTCYASSETSINDICATOR $CHAR50.
		        TLOBANKRUPTCYORIGINALCHAPTER $CHAR50.
		        TLOBANKRUPTCYCONVERTEDCHAPTER $CHAR50.
		        TLOBANKRUPTCYUPDATEDDATE $CHAR50.
		        TLOBANKRUPTCYTRUSTEEFIRSTNAME $CHAR50.
		        TLOBANKRUPTCYTRUSTEEMIDDLENAME $CHAR50.
		        TLOBANKRUPTCYTRUSTEELASTNAME $CHAR50.
		        TLOBANKRUPTCYTRUSTEENAMESUFFIX $CHAR50.
		        TLOBANKRUPTCYJUDGEINITIALS $CHAR50.
		        TLOBANKRUPTCYCOURTNAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYFIRSTNAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYMIDDLENAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYLASTNAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYNAMESUFFIX $CHAR50.
		        TLOBANKRUPTCYPROSEINDICATOR $CHAR50.
		        TLOBANKRUPTCYLAWFIRM $CHAR50.
		        TLOBANKRUPTCYBARDATE $CHAR50.
		        TLOADDRESS1LINE1 $CHAR50.
		        TLOADDRESS1LINE2 $CHAR50.
		        TLOADDRESS1LINE3 $CHAR50.
		        TLOADDRESS1CITY  $CHAR50.
		        TLOADDRESS1STATE $CHAR50.
		        TLOADDRESS1ZIP   $CHAR50.
		        TLOADDRESS1COUNTY $CHAR50.
		        TLOADDRESS1DATEFIRSTSEEN $CHAR50.
		        TLOADDRESS1DATELASTSEEN $CHAR50.
		        TLOADDRESS2LINE1 $CHAR50.
		        TLOADDRESS2LINE2 $CHAR50.
		        TLOADDRESS2LINE3 $CHAR50.
		        TLOADDRESS2CITY  $CHAR50.
		        TLOADDRESS2STATE $CHAR50.
		        TLOADDRESS2ZIP   $CHAR50.
		        TLOADDRESS2COUNTY $CHAR50.
		        TLOADDRESS2DATEFIRSTSEEN $CHAR50.
		        TLOADDRESS2DATELASTSEEN $CHAR50.
		        TLOPHONE1       $CHAR50.
		        TLOPHONE1PHONETYPE $CHAR50.
		        TLOPHONE1SCORE   $CHAR50.
		        TLOPHONE2        $CHAR50.
		        TLOPHONE2PHONETYPE $CHAR50.
		        TLOPHONE2SCORE   $CHAR50.
		        TLOPHONE3        $CHAR50.
		        TLOPHONE3PHONETYPE $CHAR50.
		        TLOPHONE3SCORE   $CHAR50.
		        MATCHCODES       $CHAR50.
		        BOB_TOOMANYHITS  $CHAR50. ;
		    INFORMAT
		        CUSTOMER_ACCOUNT $CHAR50.
		        FIRST_NAME       $CHAR50.
		        MIDDLE_NAME      $CHAR50.
		        LAST_NAME        $CHAR50.
		        SUFFIX           $CHAR50.
		        SSN              $CHAR50.
		        ADDRESS_1        $CHAR50.
		        ADDRESS_2        $CHAR50.
		        CITY             $CHAR50.
		        STATE            $CHAR50.
		        ZIP              $CHAR50.
		        TLODATEOFDEATH   $CHAR50.
		        TLOBANKRUPTCYMATCHCODES $CHAR50.
		        TLOBANKRUPTCYCHAPTER $CHAR50.
		        TLOBANKRUPTCYDEBTORNAME $CHAR50.
		        TLOBANKRUPTCYCASENUMBER $CHAR50.
		        TLOBANKRUPTCYFILEDATE $CHAR50.
		        TLOBANKRUPTCYDISCHARGEDATE $CHAR50.
		        TLOBANKRUPTCYCLOSEDDATE $CHAR50.
		        TLOBANKRUPTCYNOTICETYPE $CHAR50.
		        TLOBANKRUPTCYATTORNEYNAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESS $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSLINE $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRES_0001 $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRES_0002 $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSCITY $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSSTAT $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSZIP $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSZIP4 $CHAR50.
		        TLOBANKRUPTCYATTORNEYPHONE $CHAR50.
		        TLOBANKRUPTCYCOURTDISTRICT $CHAR50.
		        TLOBANKRUPTCYCOURTDIVISION $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESS $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSLINE1 $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSLINE2 $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSLINE3 $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSCITY $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSSTATE $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSZIP $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSZIP4 $CHAR50.
		        TLOBANKRUPTCYCOURTPHONE $CHAR50.
		        TLOBANKRUPTCYTRUSTEENAME $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESS $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE1 $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE2 $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE3 $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSCITY $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSSTATE $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSZIP $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSZIP4 $CHAR50.
		        TLOBANKRUPTCYTRUSTEEPHONE $CHAR50.
		        TLOBANKRUPTCYDISMISSEDDATE $CHAR50.
		        TLOBANKRUPTCYTRANSFERREDDATE $CHAR50.
		        TLOBANKRUPTCYPLACEHOLDER $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORFULLNA $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORFIRSTN $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORLASTNA $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORMIDDLE $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORNAMESU $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORFULLAD $CHAR100.
		        TLOBANKRUPTCYPRIMARYDEBTORADDRES $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0001 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0002 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0003 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0004 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0005 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0006 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORPHONE $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORSSN $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORAKA1 $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORAKA2 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORFULL $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORFIRS $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORLAST $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORMIDD $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORNAME $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0001 $CHAR100.
		        TLOBANKRUPTCYSECONDARYDEBTORADDR $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0002 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0003 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0004 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0005 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0006 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0007 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORPHON $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORSSN $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORAKA1 $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORAKA2 $CHAR50.
		        TLOBANKRUPTCYFLAG $CHAR50.
		        TLOBANKRUPTCY341DATE $CHAR50.
		        TLOBANKRUPTCY341TIME $CHAR50.
		        TLOBANKRUPTCY341ADDRESSLINE1 $CHAR50.
		        TLOBANKRUPTCY341ADDRESSLINE2 $CHAR50.
		        TLOBANKRUPTCY341ADDRESSLINE3 $CHAR50.
		        TLOBANKRUPTCY341ADDRESSCITY $CHAR50.
		        TLOBANKRUPTCY341ADDRESSSTATE $CHAR50.
		        TLOBANKRUPTCY341ADDRESSZIP $CHAR50.
		        TLOBANKRUPTCY341ADDRESSZIP4 $CHAR50.
		        TLOBANKRUPTCY341FULLADDRESS $CHAR50.
		        TLOBANKRUPTCYVOLUNTARYFLAG $CHAR50.
		        TLOBANKRUPTCYASSETSINDICATOR $CHAR50.
		        TLOBANKRUPTCYORIGINALCHAPTER $CHAR50.
		        TLOBANKRUPTCYCONVERTEDCHAPTER $CHAR50.
		        TLOBANKRUPTCYUPDATEDDATE $CHAR50.
		        TLOBANKRUPTCYTRUSTEEFIRSTNAME $CHAR50.
		        TLOBANKRUPTCYTRUSTEEMIDDLENAME $CHAR50.
		        TLOBANKRUPTCYTRUSTEELASTNAME $CHAR50.
		        TLOBANKRUPTCYTRUSTEENAMESUFFIX $CHAR50.
		        TLOBANKRUPTCYJUDGEINITIALS $CHAR50.
		        TLOBANKRUPTCYCOURTNAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYFIRSTNAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYMIDDLENAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYLASTNAME $CHAR50.
		        TLOBANKRUPTCYATTORNEYNAMESUFFIX $CHAR50.
		        TLOBANKRUPTCYPROSEINDICATOR $CHAR50.
		        TLOBANKRUPTCYLAWFIRM $CHAR50.
		        TLOBANKRUPTCYBARDATE $CHAR50.
		        TLOADDRESS1LINE1 $CHAR50.
		        TLOADDRESS1LINE2 $CHAR50.
		        TLOADDRESS1LINE3 $CHAR50.
		        TLOADDRESS1CITY  $CHAR50.
		        TLOADDRESS1STATE $CHAR50.
		        TLOADDRESS1ZIP   $CHAR50.
		        TLOADDRESS1COUNTY $CHAR50.
		        TLOADDRESS1DATEFIRSTSEEN $CHAR50.
		        TLOADDRESS1DATELASTSEEN $CHAR50.
		        TLOADDRESS2LINE1 $CHAR50.
		        TLOADDRESS2LINE2 $CHAR50.
		        TLOADDRESS2LINE3 $CHAR50.
		        TLOADDRESS2CITY  $CHAR50.
		        TLOADDRESS2STATE $CHAR50.
		        TLOADDRESS2ZIP   $CHAR50.
		        TLOADDRESS2COUNTY $CHAR50.
		        TLOADDRESS2DATEFIRSTSEEN $CHAR50.
		        TLOADDRESS2DATELASTSEEN $CHAR50.
		        TLOPHONE1        $CHAR50.
		        TLOPHONE1PHONETYPE $CHAR50.
		        TLOPHONE1SCORE   $CHAR50.
		        TLOPHONE2        $CHAR50.
		        TLOPHONE2PHONETYPE $CHAR50.
		        TLOPHONE2SCORE   $CHAR50.
		        TLOPHONE3        $CHAR50.
		        TLOPHONE3PHONETYPE $CHAR50.
		        TLOPHONE3SCORE   $CHAR50.
		        MATCHCODES       $CHAR50.
		        BOB_TOOMANYHITS  $CHAR50. ;
/*		INFILE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\DATA SERVICES OUTPUTS\TLO_waterfall_input_EBG_20180404_1_append.csv"*/
		  INFILE "&FILE_USE"
			DLM=','
		    MISSOVER
		    DSD
			FIRSTOBS=2;
		    INPUT
		        CUSTOMER_ACCOUNT : $CHAR50.
		        FIRST_NAME       : $CHAR50.
		        MIDDLE_NAME      : $CHAR50.
		        LAST_NAME        : $CHAR50.
		        SUFFIX           : $CHAR50.
		        SSN              : $CHAR50.
		        ADDRESS_1        : $CHAR50.
		        ADDRESS_2        : $CHAR50.
		        CITY             : $CHAR50.
		        STATE            : $CHAR50.
		        ZIP              : $CHAR50.
		        TLODATEOFDEATH   : $CHAR50.
		        TLOBANKRUPTCYMATCHCODES : $CHAR6.
		        TLOBANKRUPTCYCHAPTER : $CHAR50.
		        TLOBANKRUPTCYDEBTORNAME : $CHAR50.
		        TLOBANKRUPTCYCASENUMBER : $CHAR50.
		        TLOBANKRUPTCYFILEDATE : $CHAR50.
		        TLOBANKRUPTCYDISCHARGEDATE : $CHAR50.
		        TLOBANKRUPTCYCLOSEDDATE : $CHAR50.
		        TLOBANKRUPTCYNOTICETYPE : $CHAR50.
		        TLOBANKRUPTCYATTORNEYNAME : $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESS : $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSLINE : $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRES_0001 : $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRES_0002 : $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSCITY : $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSSTAT : $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSZIP : $CHAR50.
		        TLOBANKRUPTCYATTORNEYADDRESSZIP4 : $CHAR50.
		        TLOBANKRUPTCYATTORNEYPHONE : $CHAR50.
		        TLOBANKRUPTCYCOURTDISTRICT : $CHAR50.
		        TLOBANKRUPTCYCOURTDIVISION : $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESS : $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSLINE1 : $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSLINE2 : $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSLINE3 : $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSCITY : $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSSTATE : $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSZIP : $CHAR50.
		        TLOBANKRUPTCYCOURTADDRESSZIP4 : $CHAR50.
		        TLOBANKRUPTCYCOURTPHONE : $CHAR50.
		        TLOBANKRUPTCYTRUSTEENAME : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESS : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE1 : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE2 : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSLINE3 : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSCITY : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSSTATE : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSZIP : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEADDRESSZIP4 : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEPHONE : $CHAR50.
		        TLOBANKRUPTCYDISMISSEDDATE : $CHAR50.
		        TLOBANKRUPTCYTRANSFERREDDATE : $CHAR50.
		        TLOBANKRUPTCYPLACEHOLDER : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORFULLNA : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORFIRSTN : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORLASTNA : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORMIDDLE : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORNAMESU : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORFULLAD : $CHAR100.
		        TLOBANKRUPTCYPRIMARYDEBTORADDRES : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0001 : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0002 : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0003 : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0004 : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0005 : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORA_0006 : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORPHONE : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORSSN : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORAKA1 : $CHAR50.
		        TLOBANKRUPTCYPRIMARYDEBTORAKA2 : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORFULL : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORFIRS : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORLAST : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORMIDD : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORNAME : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0001 : $CHAR100.
		        TLOBANKRUPTCYSECONDARYDEBTORADDR : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0002 : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0003 : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0004 : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0005 : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0006 : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTO_0007 : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORPHON : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORSSN : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORAKA1 : $CHAR50.
		        TLOBANKRUPTCYSECONDARYDEBTORAKA2 : $CHAR50.
		        TLOBANKRUPTCYFLAG : $CHAR50.
		        TLOBANKRUPTCY341DATE : $CHAR50.
		        TLOBANKRUPTCY341TIME : $CHAR50.
		        TLOBANKRUPTCY341ADDRESSLINE1 : $CHAR50.
		        TLOBANKRUPTCY341ADDRESSLINE2 : $CHAR50.
		        TLOBANKRUPTCY341ADDRESSLINE3 : $CHAR50.
		        TLOBANKRUPTCY341ADDRESSCITY : $CHAR50.
		        TLOBANKRUPTCY341ADDRESSSTATE : $CHAR50.
		        TLOBANKRUPTCY341ADDRESSZIP : $CHAR50.
		        TLOBANKRUPTCY341ADDRESSZIP4 : $CHAR50.
		        TLOBANKRUPTCY341FULLADDRESS : $CHAR50.
		        TLOBANKRUPTCYVOLUNTARYFLAG : $CHAR50.
		        TLOBANKRUPTCYASSETSINDICATOR : $CHAR50.
		        TLOBANKRUPTCYORIGINALCHAPTER : $CHAR50.
		        TLOBANKRUPTCYCONVERTEDCHAPTER : $CHAR50.
		        TLOBANKRUPTCYUPDATEDDATE : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEFIRSTNAME : $CHAR50.
		        TLOBANKRUPTCYTRUSTEEMIDDLENAME : $CHAR50.
		        TLOBANKRUPTCYTRUSTEELASTNAME : $CHAR50.
		        TLOBANKRUPTCYTRUSTEENAMESUFFIX : $CHAR50.
		        TLOBANKRUPTCYJUDGEINITIALS : $CHAR50.
		        TLOBANKRUPTCYCOURTNAME : $CHAR50.
		        TLOBANKRUPTCYATTORNEYFIRSTNAME : $CHAR50.
		        TLOBANKRUPTCYATTORNEYMIDDLENAME : $CHAR50.
		        TLOBANKRUPTCYATTORNEYLASTNAME : $CHAR50.
		        TLOBANKRUPTCYATTORNEYNAMESUFFIX : $CHAR50.
		        TLOBANKRUPTCYPROSEINDICATOR : $CHAR50.
		        TLOBANKRUPTCYLAWFIRM : $CHAR50.
		        TLOBANKRUPTCYBARDATE : $CHAR50.
		        TLOADDRESS1LINE1 : $CHAR50.
		        TLOADDRESS1LINE2 : $CHAR50.
		        TLOADDRESS1LINE3 : $CHAR50.
		        TLOADDRESS1CITY  : $CHAR50.
		        TLOADDRESS1STATE : $CHAR50.
		        TLOADDRESS1ZIP   : $CHAR50.
		        TLOADDRESS1COUNTY : $CHAR50.
		        TLOADDRESS1DATEFIRSTSEEN : $CHAR50.
		        TLOADDRESS1DATELASTSEEN : $CHAR50.
		        TLOADDRESS2LINE1 : $CHAR50.
		        TLOADDRESS2LINE2 : $CHAR50.
		        TLOADDRESS2LINE3 : $CHAR50.
		        TLOADDRESS2CITY  : $CHAR50.
		        TLOADDRESS2STATE : $CHAR50.
		        TLOADDRESS2ZIP   : $CHAR50.
		        TLOADDRESS2COUNTY : $CHAR50.
		        TLOADDRESS2DATEFIRSTSEEN : $CHAR50.
		        TLOADDRESS2DATELASTSEEN : $CHAR50.
		        TLOPHONE1        : $CHAR50.
		        TLOPHONE1PHONETYPE : $CHAR50.
		        TLOPHONE1SCORE   : $CHAR50.
		        TLOPHONE2        : $CHAR50.
		        TLOPHONE2PHONETYPE : $CHAR9.
		        TLOPHONE2SCORE   : $CHAR50.
		        TLOPHONE3        : $CHAR50.
		        TLOPHONE3PHONETYPE : $CHAR50.
		        TLOPHONE3SCORE   : $CHAR50.
		        MATCHCODES       : $CHAR50.
		        BOB_TOOMANYHITS  : $CHAR50. ;
		RUN;

%MEND;