OPTIONS MPRINT MLOGIC SYMBOLGEN VALIDVARNAME=ANY;

FILENAME GEO_IN PIPE 'DIR "C:\Users\john.lodmell\OneDrive - emergentbusinessgroup.com\New Business\Galaxy\2018_05_25_Placement\Prosper_nbr2\CLIENT_OTHER_DATA\*.CSV" /B ';

/*JUSTIN'S PATH*/
/*FILENAME GEO_IN PIPE 'DIR "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST2\CLIENT_OTHER_DATA\*.CSV" /B ';*/

%LET FILE_LOC_IN = "&MASTER_DIR.\CLIENT_OTHER_DATA";

%LET DATE=%SYSFUNC(INTNX(DAY,%SYSFUNC(TODAY()),0,END),DATE7.);
%PUT &DATE;

DATA DIRLIST_GEO_IN;
       INFILE GEO_IN LRECL=200 TRUNCOVER;
       INPUT FILE_NAME $150.;
	   LENGTH = LENGTH(FILE_NAME);
	   FILE_NAME_FULL = &FILE_LOC_IN.||"\"||FILE_NAME;
	   EXTENSION = SCAN(TRANWRD(COMPRESS(FILE_NAME_FULL),'.',' '),2);
	   CLIENT_NAME = UPCASE(SCAN(TRANWRD(FILE_NAME,'_',' '),1));
RUN;

PROC SQL;
	SELECT COUNT(FILE_NAME) INTO: COUNT_OTHER_IN
	FROM DIRLIST_GEO_IN
;
QUIT;

PROC SORT DATA=DIRLIST_GEO_IN NODUPKEY;
BY CLIENT_NAME FILE_NAME_FULL;
RUN;

DATA COUNT_FILES_IN;
	SET DIRLIST_GEO_IN;
	BY CLIENT_NAME FILE_NAME_FULL;
	RETAIN COUNT 0;
	IF FIRST.CLIENT_NAME THEN COUNT = 0;
	COUNT+1;
	TOTAL_COUNTER = COUNT;
/*	LAST_CLIENT_DATA = LAST.CLIENT_NAME;*/
RUN;

%MACRO CHECK_FIRST_FILE_IN(FILE=,TOTAL_COUNTER=,FILE_NAME=,EXTENSION=);

	%IF &TOTAL_COUNTER.= 1  AND %EVAL(&COUNT_OTHER_IN. >= 1) %THEN 
		%DO;
			
			%PUT &FILE;
			%PUT &EXTENSION;

			DATA _NULL_;
				CALL SYMPUTX("FILE_USE","&FILE",'G');
				CALL SYMPUTX("TOTAL_COUNTER_USE",&TOTAL_COUNTER.,'G');
			RUN;

		/*IMPORT CLIENT OTHER DATA*/

			*May need to remember to update this hardcoded address in the future if the macro assignment is not fixed;
			PROC IMPORT DATAFILE="C:\Users\john.lodmell\OneDrive - emergentbusinessgroup.com\New Business\New_Load_Process_Test\CLIENT_OTHER_DATA\LendingClub_OTHER_DATA.csv"
				DBMS=csv
				REPLACE
				OUT=OTHER_DATA_IMPORT;
				GUESSINGROWS=1000;
				GETNAMES=YES;
			RUN;

			

			PROC CONTENTS DATA=OTHER_DATA_IMPORT NOPRINT
					OUT=OTHER_DATA_IMPORT_CONTENTS;
			RUN;

			Proc sort data=OTHER_DATA_IMPORT_CONTENTS;
				by varnum;
			run;

			PROC SQL;
				SELECT NAME INTO: VARS SEPARATED BY " $CHAR50. "
				FROM OTHER_DATA_IMPORT_CONTENTS
			;
			QUIT;

			PROC SQL;
				SELECT NAME INTO: VARS_COLON SEPARATED BY " : $CHAR50. "
				FROM OTHER_DATA_IMPORT_CONTENTS
			;
			QUIT;

			PROC SQL;
				SELECT NAME INTO: VARS_LENGTH SEPARATED BY " $50. "
				FROM OTHER_DATA_IMPORT_CONTENTS
			;
			QUIT;

			%PUT &VARS;
			%PUT &VARS_COLON;
			%PUT &VARS_LENGTH;


			DATA OTHER_DATA_IMPORT_REAL;
			    LENGTH
				&VARS_LENGTH. $50.;
			    FORMAT
				&VARS. $CHAR50.;	
			    INFORMAT
				&VARS. $CHAR50.;
/*			    INFILE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST2\CLIENT_OTHER_DATA\Book2.csv"*/
					  INFILE "&FILE_USE"
						DLM=','
				        MISSOVER
				        DSD
						FIRSTOBS=2;
			    INPUT
				&VARS_COLON. : $CHAR50.;
			RUN;

		%END;

	%ELSE %IF &TOTAL_COUNTER. ^= 1 AND %EVAL(&COUNT_OTHER_IN. >= 1) %THEN 
		%DO;

			%PUT &FILE;
			%PUT &EXTENSION;

			DATA _NULL_;
				CALL SYMPUTX("FILE_USE","&FILE",'G');
				CALL SYMPUTX("TOTAL_COUNTER_USE",&TOTAL_COUNTER.,'G');
			RUN;

		/*IMPORT CLIENT OTHER DATA*/
			PROC IMPORT DATAFILE="&FILE_USE"
				DBMS=csv
				REPLACE
				OUT=OTHER_DATA_IMPORT_&TOTAL_COUNTER.;
				GUESSINGROWS=1000;
				GETNAMES=YES;
			RUN;

			PROC CONTENTS DATA=OTHER_DATA_IMPORT_&TOTAL_COUNTER. NOPRINT
					OUT=OTHER_DATA_IMPORT_CONTENTS_&TOTAL_COUNTER_USE;
			RUN;

			PROC SQL;
				SELECT NAME INTO: VARS SEPARATED BY " $CHAR50. "
				FROM OTHER_DATA_IMPORT_CONTENTS_&TOTAL_COUNTER_USE
			;
			QUIT;

			PROC SQL;
				SELECT NAME INTO: VARS_COLON SEPARATED BY " : $CHAR50. "
				FROM OTHER_DATA_IMPORT_CONTENTS_&TOTAL_COUNTER_USE
			;
			QUIT;

			PROC SQL;
				SELECT NAME INTO: VARS_LENGTH SEPARATED BY " $50. "
				FROM OTHER_DATA_IMPORT_CONTENTS_&TOTAL_COUNTER_USE
			;
			QUIT;

			%PUT &VARS;
			%PUT &VARS_COLON;
			%PUT &VARS_LENGTH;


			DATA OTHER_DATA_IMPORT_REAL_&TOTAL_COUNTER.;
			    LENGTH
				&VARS_LENGTH. $50.;
			    FORMAT
				&VARS. $CHAR50.;	
			    INFORMAT
				&VARS. $CHAR50.;
/*			    INFILE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\ENVIRONMENT\BEAM\IMPORTS\PIPPED_BEAM.TXT"*/
					  INFILE "&FILE_USE"
						DLM=','
				        MISSOVER
				        DSD
						FIRSTOBS=2;
			    INPUT
				&VARS_COLON. : $CHAR50.;
			RUN;

			PROC APPEND BASE=OTHER_DATA_IMPORT_REAL DATA=OTHER_DATA_IMPORT_REAL_&TOTAL_COUNTER. FORCE;
			RUN;

		%END;
%MEND;

PROC SQL;
	DROP TABLE OTHER_DATA_IMPORT;
QUIT;


DATA _NULL_;
	SET COUNT_FILES_IN;
	CALL EXECUTE('%NRSTR(%CHECK_FIRST_FILE_IN(FILE='||FILE_NAME_FULL||',TOTAL_COUNTER='||PUT(COUNT,8.)||',FILE_NAME='||FILE_NAME||',EXTENSION='||EXTENSION||'))');
RUN;


