/*CREATE LN_SCRA_INPUT */

DATA LN_SCRA_INPUT_PRE (DROP=DOB);
	SET DATA_SERVICES_INPUTS_MASTER;
	DOB_USE = INPUT(DOB,MMDDYY10.);
	FORMAT DOB_USE YYMMDD10.;
	DROP AGREEMENT_DATE;
RUN;

DATA LN_SCRA_INPUT_PRE2 (DROP=DOB_USE);
	SET LN_SCRA_INPUT_PRE;
	DOB_1 = DOB_USE;
	FORMAT DOB_1 YYMMDD10.;
RUN;

DATA LN_SCRA_INPUT (DROP=DOB_1);
	SET LN_SCRA_INPUT_PRE2;
	DOB = COMPRESS(PUT(DOB_1,YYMMDD10.),"1234567890",'KIS');
RUN;

