OPTIONS NOXWAIT;

%LET TRIGGER = 1;

%MACRO DIRECTORIES(SHOULD_RUN=);

	%IF &SHOULD_RUN. = 1 %THEN 
		%DO;
			%SYSEXEC MKDIR "&MASTER_DIR.\STANDARDIZED CLIENT FILES"
						   "&MASTER_DIR.\DATA SERVICES OUTPUTS"
						   "&MASTER_DIR.\IMPORT FROM BEAM"
						   "&MASTER_DIR.\SCRUB EXPORTS\&DATE."
						   "&MASTER_DIR.\RETURN MAIL\&DATE."
						   "&MASTER_DIR.\CUSTOM PROPERTY INPUT\&DATE."
						   "&MASTER_DIR.\EXCEPTION FILES\&DATE."
						   "&MASTER_DIR.\EXPORT TO BEAM\&DATE."					
						   "&MASTER_DIR.\DATA SERVICES INPUTS\&DATE."
						   "&MASTER_DIR.\CLIENT_OTHER_DATA\&DATE.";
/*						   "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\DATA SERVICES BACKUPS\&DATE.";*/

		%END;

%MEND;

%DIRECTORIES(SHOULD_RUN=&TRIGGER)