/*------------------------------------------------------------------

	PURPOSE: GENERAL LOCATION OF PATH INFORMATION BETWEEN JUSTIN'S
			 AND JOHN'S EPG SAS SESSIONS

*-------------------------------------------------------------------*/
%GLOBAL MASTER_DIR 
		WHEREPRGMSAT 
		BEAM_EXPORT_PATH 
		DATA_SERVICE_PATH
		EXCEPTION_PATH
		RETURN_MAIL_PATH
		CUSTOM_PROPERTY_PATH
		SCRUB_PATH;



/*JOHNS PATHS:*/

%LET WHEREPRGMSAT = \\NXX-SWS-AD001\Users$\john.lodmell\Documents\GitHub\Portfolio_Load\Programs; 

/*MASTER PATH SHOULD BE ONLY PATH THAT YOU NEED TO CHANGE*/
%LET MASTER_DIR = C:\Users\john.lodmell\OneDrive - emergentbusinessgroup.com\New Business\New_Load_Process_Test;

/*THESE SHOULD BE CREATED BY THEMSELVES WITH THE DIRECTORY PROGRAM AFTER YOU HAVE SET THE MASTER_DIR*/
%LET BEAM_EXPORT_PATH = &MASTER_DIR.\EXPORT TO BEAM\&DATE.\;
%LET DATA_SERVICE_PATH = &MASTER_DIR.\DATA SERVICES INPUTS\&DATE.\;
%LET EXCEPTION_PATH = &MASTER_DIR.\EXCEPTION FILES\&DATE.;
%LET RETURN_MAIL_PATH = &MASTER_DIR.\RETURN MAIL\&DATE.;
%LET CUSTOM_PROPERTY_PATH = &MASTER_DIR.\CUSTOM PROPERTY INPUT\&DATE.;
%LET SCRUB_PATH = &MASTER_DIR.\SCRUB EXPORTS\&DATE.;


/*------------------------*END OF JOHN'S PATHS-----------------------------------------*/




/*JUSTINS PATHS:*/

/*MASTER_DIR/WHEREPRGMSAT SHOULD BE ONLY PATH THAT YOU NEED TO CHANGE*/
/*%LET MASTER_DIR = E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST;*/
/*%LET WHEREPRGMSAT = E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PROGRAMS\PROGRAMS;*/
/*%PUT &WHEREPRGMSAT;*/
/**/
/**/
/*%LET BEAM_EXPORT_PATH = &MASTER_DIR\EXPORT TO BEAM\&DATE.\;*/
/*%LET DATA_SERVICE_PATH = &MASTER_DIR\DATA SERVICES INPUTS\&DATE.\;*/
/*%LET EXCEPTION_PATH = &MASTER_DIR\EXCEPTION FILES\&DATE.;*/
/*%LET RETURN_MAIL_PATH = &MASTER_DIR\RETURN MAIL\&DATE.;*/
/*%LET CUSTOM_PROPERTY_PATH = &MASTER_DIR\CUSTOM PROPERTY INPUT\&DATE.;*/
/*%LET SCRUB_PATH = &MASTER_DIR\SCRUB EXPORTS\&DATE.;*/



	