/*GOAL OF THIS PROGRAM IS TOO ALLOW EASIER TIME OF IMPORTING BEFORE YOU MAKE EVERYTHING PIPE DELIMITED */
/*THIS PROGRAM WILL SORT THE COLUMNS IN THE SAME ORDER THAT THE DRIVER REQUIRES*/

OPTIONS MPRINT MLOGIC SYMBOLGEN VALIDVARNAME=ANY;

FILENAME GEO_IN PIPE 'DIR "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\ORGANIZE CLIENT PORTFOLIO FILES\*.TXT" /B ';

%LET FILE_LOC_IN = "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\EBG\1_PORTFOLIO_FILE_STANDARDIZATION\PRODUCTION ENVIRONMENT TEST\ORGANIZE CLIENT PORTFOLIO FILES";

%LET DATE=%SYSFUNC(INTNX(DAY,%SYSFUNC(TODAY()),0,END),DATE7.);
%PUT &DATE;

DATA DIRLIST_GEO_IN;
       INFILE GEO_IN LRECL=200 TRUNCOVER;
       INPUT FILE_NAME $150.;
	   LENGTH = LENGTH(FILE_NAME);
	   FILE_NAME_FULL = &FILE_LOC_IN.||"\"||FILE_NAME;
	   EXTENSION = SCAN(TRANWRD(COMPRESS(FILE_NAME_FULL),'.',' '),2);
RUN;

PROC SQL;
	SELECT COUNT(FILE_NAME) INTO: COUNT_BEAM_IN
	FROM DIRLIST_GEO_IN
;
QUIT;

PROC SORT DATA=DIRLIST_GEO_IN NODUPKEY;
BY FILE_NAME_FULL ;
RUN;

DATA COUNT_FILES_IN;
	SET DIRLIST_GEO_IN;
	BY FILE_NAME_FULL;
	RETAIN COUNT 0;
	COUNT+1;
	TOTAL_COUNTER = COUNT;
	NEW_FILE_NAME = SCAN((TRANWRD(FILE_NAME,'.',' ')),1);
RUN;

%MACRO CHECK_FIRST_FILE_IN(FILE=,TOTAL_COUNTER=,FILE_NAME=,EXTENSION=,NEW_FILE_NAME=);

	%IF &TOTAL_COUNTER.= 1  %THEN 
		%DO;
			
			%PUT &FILE;
			%PUT &EXTENSION;

			DATA _NULL_;
				CALL SYMPUTX("FILE_USE","&FILE.",'G');
				CALL SYMPUTX("TOTAL_COUNTER_USE",&TOTAL_COUNTER.,'G');
				CALL SYMPUTX("NEW_FILE_NAME_USE","&NEW_FILE_NAME.",'G');
			RUN;
			
			/*RAW CLIENT PORTFOLIO*/
			%INCLUDE "&WHEREPRGMSAT.\ORGANIZE CLIENT PORTFOLIO IMPORT.SAS";
				%ORGANIZE_IMPORT

		%END;

	%ELSE %IF &TOTAL_COUNTER. ^= 1 %THEN 
		%DO;

			%PUT &FILE;
			%PUT &EXTENSION;

			DATA _NULL_;
				CALL SYMPUTX("FILE_USE","&FILE.",'G');
				CALL SYMPUTX("TOTAL_COUNTER_USE",&TOTAL_COUNTER.,'G');
				CALL SYMPUTX("NEW_FILE_NAME_USE","&NEW_FILE_NAME.",'G');
			RUN;	

			/*RAW CLIENT PORTFOLIO*/
			%INCLUDE "&WHEREPRGMSAT.\ORGANIZE CLIENT PORTFOLIO IMPORT.SAS";
				%ORGANIZE_IMPORT

		%END;
%MEND;

DATA _NULL_;
	SET COUNT_FILES_IN;
	CALL EXECUTE('%NRSTR(%CHECK_FIRST_FILE_IN(FILE='||FILE_NAME_FULL||',TOTAL_COUNTER='||PUT(COUNT,8.)||',FILE_NAME='||FILE_NAME||',EXTENSION='||EXTENSION||',NEW_FILE_NAME='||NEW_FILE_NAME||'))');
RUN;