/*AT THIS POINT WE SHOULD HAVE 4 FILES

	1) BANKRUPTCY FILE
	2) LITIGIOUS FILE
	3) DECEASED
	4) MILITARY FILE					*/


/*NEED TO ROLLUP THESE FILES AND OUTPUT THEM*/

/*I MADE THIS DIRECTORY AT BEGINNING OF PROGRAM*/

/*%LET EXCEPTION_PATH = &MASTER_DIR.\EXCEPTION FILES\&DATE.;*/
/*%PUT &EXCEPTION_PATH;*/

/*BANKRUPTCY FILE*/
PROC EXPORT DATA=BANKRUPTCY_FINAL_EXCEPTIONS
	OUTFILE="&EXCEPTION_PATH.\EXCEPTIONS_&DATE..XLSX"
	DBMS=XLSX
	REPLACE
	LABEL;
	SHEET="Bankruptcy";
RUN;

/*GET DECEASED FILE*/
PROC EXPORT DATA=DECEASED_FINAL_EXCEPTIONS
	OUTFILE="&EXCEPTION_PATH.\EXCEPTIONS_&DATE..XLSX"
	DBMS=XLSX
	REPLACE
	LABEL;
	SHEET="Deceased";
RUN;

/*GET LITIGIOUS FILE*/
PROC EXPORT DATA=LITIGIOUS_FINAL_EXCEPTIONS
	OUTFILE="&EXCEPTION_PATH.\EXCEPTIONS_&DATE..XLSX"
	DBMS=XLSX
	REPLACE
	LABEL;
	SHEET="Lawsuit_Risk";
RUN;

/*GET MILITARY FILE*/
PROC EXPORT DATA=MILITARY_FINAL_EXCEPTIONS
	OUTFILE="&EXCEPTION_PATH.\EXCEPTIONS_&DATE..XLSX"
	DBMS=XLSX
	REPLACE
	LABEL;
	SHEET="Other";
RUN;
